/**
 * @fileoverview gRPC-Web generated client stub for google.api.servicecontrol.v2
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.1
// 	protoc              v3.19.1
// source: google/api/servicecontrol/v2/service_controller.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var google_api_annotations_pb = require('../../../../google/api/annotations_pb.js')

var google_api_client_pb = require('../../../../google/api/client_pb.js')

var google_rpc_context_attribute_context_pb = require('../../../../google/rpc/context/attribute_context_pb.js')

var google_rpc_status_pb = require('../../../../google/rpc/status_pb.js')
const proto = {};
proto.google = {};
proto.google.api = {};
proto.google.api.servicecontrol = {};
proto.google.api.servicecontrol.v2 = require('./service_controller_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.google.api.servicecontrol.v2.ServiceControllerClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.google.api.servicecontrol.v2.ServiceControllerPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.api.servicecontrol.v2.CheckRequest,
 *   !proto.google.api.servicecontrol.v2.CheckResponse>}
 */
const methodDescriptor_ServiceController_Check = new grpc.web.MethodDescriptor(
  '/google.api.servicecontrol.v2.ServiceController/Check',
  grpc.web.MethodType.UNARY,
  proto.google.api.servicecontrol.v2.CheckRequest,
  proto.google.api.servicecontrol.v2.CheckResponse,
  /**
   * @param {!proto.google.api.servicecontrol.v2.CheckRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.google.api.servicecontrol.v2.CheckResponse.deserializeBinary
);


/**
 * @param {!proto.google.api.servicecontrol.v2.CheckRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.api.servicecontrol.v2.CheckResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.api.servicecontrol.v2.CheckResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.google.api.servicecontrol.v2.ServiceControllerClient.prototype.check =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/google.api.servicecontrol.v2.ServiceController/Check',
      request,
      metadata || {},
      methodDescriptor_ServiceController_Check,
      callback);
};


/**
 * @param {!proto.google.api.servicecontrol.v2.CheckRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.api.servicecontrol.v2.CheckResponse>}
 *     Promise that resolves to the response
 */
proto.google.api.servicecontrol.v2.ServiceControllerPromiseClient.prototype.check =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/google.api.servicecontrol.v2.ServiceController/Check',
      request,
      metadata || {},
      methodDescriptor_ServiceController_Check);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.api.servicecontrol.v2.ReportRequest,
 *   !proto.google.api.servicecontrol.v2.ReportResponse>}
 */
const methodDescriptor_ServiceController_Report = new grpc.web.MethodDescriptor(
  '/google.api.servicecontrol.v2.ServiceController/Report',
  grpc.web.MethodType.UNARY,
  proto.google.api.servicecontrol.v2.ReportRequest,
  proto.google.api.servicecontrol.v2.ReportResponse,
  /**
   * @param {!proto.google.api.servicecontrol.v2.ReportRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.google.api.servicecontrol.v2.ReportResponse.deserializeBinary
);


/**
 * @param {!proto.google.api.servicecontrol.v2.ReportRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.api.servicecontrol.v2.ReportResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.api.servicecontrol.v2.ReportResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.google.api.servicecontrol.v2.ServiceControllerClient.prototype.report =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/google.api.servicecontrol.v2.ServiceController/Report',
      request,
      metadata || {},
      methodDescriptor_ServiceController_Report,
      callback);
};


/**
 * @param {!proto.google.api.servicecontrol.v2.ReportRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.api.servicecontrol.v2.ReportResponse>}
 *     Promise that resolves to the response
 */
proto.google.api.servicecontrol.v2.ServiceControllerPromiseClient.prototype.report =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/google.api.servicecontrol.v2.ServiceController/Report',
      request,
      metadata || {},
      methodDescriptor_ServiceController_Report);
};


module.exports = proto.google.api.servicecontrol.v2;

