/**
 * @fileoverview gRPC-Web generated client stub for google.iam.v1beta
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.1
// 	protoc              v3.19.1
// source: google/iam/v1beta/workload_identity_pool.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var google_api_annotations_pb = require('../../../google/api/annotations_pb.js')

var google_api_client_pb = require('../../../google/api/client_pb.js')

var google_api_field_behavior_pb = require('../../../google/api/field_behavior_pb.js')

var google_api_resource_pb = require('../../../google/api/resource_pb.js')

var google_longrunning_operations_pb = require('../../../google/longrunning/operations_pb.js')

var google_protobuf_field_mask_pb = require('google-protobuf/google/protobuf/field_mask_pb.js')
const proto = {};
proto.google = {};
proto.google.iam = {};
proto.google.iam.v1beta = require('./workload_identity_pool_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.google.iam.v1beta.WorkloadIdentityPoolsClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.google.iam.v1beta.WorkloadIdentityPoolsPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.iam.v1beta.ListWorkloadIdentityPoolsRequest,
 *   !proto.google.iam.v1beta.ListWorkloadIdentityPoolsResponse>}
 */
const methodDescriptor_WorkloadIdentityPools_ListWorkloadIdentityPools = new grpc.web.MethodDescriptor(
  '/google.iam.v1beta.WorkloadIdentityPools/ListWorkloadIdentityPools',
  grpc.web.MethodType.UNARY,
  proto.google.iam.v1beta.ListWorkloadIdentityPoolsRequest,
  proto.google.iam.v1beta.ListWorkloadIdentityPoolsResponse,
  /**
   * @param {!proto.google.iam.v1beta.ListWorkloadIdentityPoolsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.google.iam.v1beta.ListWorkloadIdentityPoolsResponse.deserializeBinary
);


/**
 * @param {!proto.google.iam.v1beta.ListWorkloadIdentityPoolsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.iam.v1beta.ListWorkloadIdentityPoolsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.iam.v1beta.ListWorkloadIdentityPoolsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.google.iam.v1beta.WorkloadIdentityPoolsClient.prototype.listWorkloadIdentityPools =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/google.iam.v1beta.WorkloadIdentityPools/ListWorkloadIdentityPools',
      request,
      metadata || {},
      methodDescriptor_WorkloadIdentityPools_ListWorkloadIdentityPools,
      callback);
};


/**
 * @param {!proto.google.iam.v1beta.ListWorkloadIdentityPoolsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.iam.v1beta.ListWorkloadIdentityPoolsResponse>}
 *     Promise that resolves to the response
 */
proto.google.iam.v1beta.WorkloadIdentityPoolsPromiseClient.prototype.listWorkloadIdentityPools =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/google.iam.v1beta.WorkloadIdentityPools/ListWorkloadIdentityPools',
      request,
      metadata || {},
      methodDescriptor_WorkloadIdentityPools_ListWorkloadIdentityPools);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.iam.v1beta.GetWorkloadIdentityPoolRequest,
 *   !proto.google.iam.v1beta.WorkloadIdentityPool>}
 */
const methodDescriptor_WorkloadIdentityPools_GetWorkloadIdentityPool = new grpc.web.MethodDescriptor(
  '/google.iam.v1beta.WorkloadIdentityPools/GetWorkloadIdentityPool',
  grpc.web.MethodType.UNARY,
  proto.google.iam.v1beta.GetWorkloadIdentityPoolRequest,
  proto.google.iam.v1beta.WorkloadIdentityPool,
  /**
   * @param {!proto.google.iam.v1beta.GetWorkloadIdentityPoolRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.google.iam.v1beta.WorkloadIdentityPool.deserializeBinary
);


/**
 * @param {!proto.google.iam.v1beta.GetWorkloadIdentityPoolRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.iam.v1beta.WorkloadIdentityPool)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.iam.v1beta.WorkloadIdentityPool>|undefined}
 *     The XHR Node Readable Stream
 */
proto.google.iam.v1beta.WorkloadIdentityPoolsClient.prototype.getWorkloadIdentityPool =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/google.iam.v1beta.WorkloadIdentityPools/GetWorkloadIdentityPool',
      request,
      metadata || {},
      methodDescriptor_WorkloadIdentityPools_GetWorkloadIdentityPool,
      callback);
};


/**
 * @param {!proto.google.iam.v1beta.GetWorkloadIdentityPoolRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.iam.v1beta.WorkloadIdentityPool>}
 *     Promise that resolves to the response
 */
proto.google.iam.v1beta.WorkloadIdentityPoolsPromiseClient.prototype.getWorkloadIdentityPool =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/google.iam.v1beta.WorkloadIdentityPools/GetWorkloadIdentityPool',
      request,
      metadata || {},
      methodDescriptor_WorkloadIdentityPools_GetWorkloadIdentityPool);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.iam.v1beta.CreateWorkloadIdentityPoolRequest,
 *   !proto.google.longrunning.Operation>}
 */
const methodDescriptor_WorkloadIdentityPools_CreateWorkloadIdentityPool = new grpc.web.MethodDescriptor(
  '/google.iam.v1beta.WorkloadIdentityPools/CreateWorkloadIdentityPool',
  grpc.web.MethodType.UNARY,
  proto.google.iam.v1beta.CreateWorkloadIdentityPoolRequest,
  google_longrunning_operations_pb.Operation,
  /**
   * @param {!proto.google.iam.v1beta.CreateWorkloadIdentityPoolRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  google_longrunning_operations_pb.Operation.deserializeBinary
);


/**
 * @param {!proto.google.iam.v1beta.CreateWorkloadIdentityPoolRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.longrunning.Operation)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.longrunning.Operation>|undefined}
 *     The XHR Node Readable Stream
 */
proto.google.iam.v1beta.WorkloadIdentityPoolsClient.prototype.createWorkloadIdentityPool =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/google.iam.v1beta.WorkloadIdentityPools/CreateWorkloadIdentityPool',
      request,
      metadata || {},
      methodDescriptor_WorkloadIdentityPools_CreateWorkloadIdentityPool,
      callback);
};


/**
 * @param {!proto.google.iam.v1beta.CreateWorkloadIdentityPoolRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.longrunning.Operation>}
 *     Promise that resolves to the response
 */
proto.google.iam.v1beta.WorkloadIdentityPoolsPromiseClient.prototype.createWorkloadIdentityPool =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/google.iam.v1beta.WorkloadIdentityPools/CreateWorkloadIdentityPool',
      request,
      metadata || {},
      methodDescriptor_WorkloadIdentityPools_CreateWorkloadIdentityPool);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.iam.v1beta.UpdateWorkloadIdentityPoolRequest,
 *   !proto.google.longrunning.Operation>}
 */
const methodDescriptor_WorkloadIdentityPools_UpdateWorkloadIdentityPool = new grpc.web.MethodDescriptor(
  '/google.iam.v1beta.WorkloadIdentityPools/UpdateWorkloadIdentityPool',
  grpc.web.MethodType.UNARY,
  proto.google.iam.v1beta.UpdateWorkloadIdentityPoolRequest,
  google_longrunning_operations_pb.Operation,
  /**
   * @param {!proto.google.iam.v1beta.UpdateWorkloadIdentityPoolRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  google_longrunning_operations_pb.Operation.deserializeBinary
);


/**
 * @param {!proto.google.iam.v1beta.UpdateWorkloadIdentityPoolRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.longrunning.Operation)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.longrunning.Operation>|undefined}
 *     The XHR Node Readable Stream
 */
proto.google.iam.v1beta.WorkloadIdentityPoolsClient.prototype.updateWorkloadIdentityPool =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/google.iam.v1beta.WorkloadIdentityPools/UpdateWorkloadIdentityPool',
      request,
      metadata || {},
      methodDescriptor_WorkloadIdentityPools_UpdateWorkloadIdentityPool,
      callback);
};


/**
 * @param {!proto.google.iam.v1beta.UpdateWorkloadIdentityPoolRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.longrunning.Operation>}
 *     Promise that resolves to the response
 */
proto.google.iam.v1beta.WorkloadIdentityPoolsPromiseClient.prototype.updateWorkloadIdentityPool =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/google.iam.v1beta.WorkloadIdentityPools/UpdateWorkloadIdentityPool',
      request,
      metadata || {},
      methodDescriptor_WorkloadIdentityPools_UpdateWorkloadIdentityPool);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.iam.v1beta.DeleteWorkloadIdentityPoolRequest,
 *   !proto.google.longrunning.Operation>}
 */
const methodDescriptor_WorkloadIdentityPools_DeleteWorkloadIdentityPool = new grpc.web.MethodDescriptor(
  '/google.iam.v1beta.WorkloadIdentityPools/DeleteWorkloadIdentityPool',
  grpc.web.MethodType.UNARY,
  proto.google.iam.v1beta.DeleteWorkloadIdentityPoolRequest,
  google_longrunning_operations_pb.Operation,
  /**
   * @param {!proto.google.iam.v1beta.DeleteWorkloadIdentityPoolRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  google_longrunning_operations_pb.Operation.deserializeBinary
);


/**
 * @param {!proto.google.iam.v1beta.DeleteWorkloadIdentityPoolRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.longrunning.Operation)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.longrunning.Operation>|undefined}
 *     The XHR Node Readable Stream
 */
proto.google.iam.v1beta.WorkloadIdentityPoolsClient.prototype.deleteWorkloadIdentityPool =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/google.iam.v1beta.WorkloadIdentityPools/DeleteWorkloadIdentityPool',
      request,
      metadata || {},
      methodDescriptor_WorkloadIdentityPools_DeleteWorkloadIdentityPool,
      callback);
};


/**
 * @param {!proto.google.iam.v1beta.DeleteWorkloadIdentityPoolRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.longrunning.Operation>}
 *     Promise that resolves to the response
 */
proto.google.iam.v1beta.WorkloadIdentityPoolsPromiseClient.prototype.deleteWorkloadIdentityPool =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/google.iam.v1beta.WorkloadIdentityPools/DeleteWorkloadIdentityPool',
      request,
      metadata || {},
      methodDescriptor_WorkloadIdentityPools_DeleteWorkloadIdentityPool);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.iam.v1beta.UndeleteWorkloadIdentityPoolRequest,
 *   !proto.google.longrunning.Operation>}
 */
const methodDescriptor_WorkloadIdentityPools_UndeleteWorkloadIdentityPool = new grpc.web.MethodDescriptor(
  '/google.iam.v1beta.WorkloadIdentityPools/UndeleteWorkloadIdentityPool',
  grpc.web.MethodType.UNARY,
  proto.google.iam.v1beta.UndeleteWorkloadIdentityPoolRequest,
  google_longrunning_operations_pb.Operation,
  /**
   * @param {!proto.google.iam.v1beta.UndeleteWorkloadIdentityPoolRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  google_longrunning_operations_pb.Operation.deserializeBinary
);


/**
 * @param {!proto.google.iam.v1beta.UndeleteWorkloadIdentityPoolRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.longrunning.Operation)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.longrunning.Operation>|undefined}
 *     The XHR Node Readable Stream
 */
proto.google.iam.v1beta.WorkloadIdentityPoolsClient.prototype.undeleteWorkloadIdentityPool =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/google.iam.v1beta.WorkloadIdentityPools/UndeleteWorkloadIdentityPool',
      request,
      metadata || {},
      methodDescriptor_WorkloadIdentityPools_UndeleteWorkloadIdentityPool,
      callback);
};


/**
 * @param {!proto.google.iam.v1beta.UndeleteWorkloadIdentityPoolRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.longrunning.Operation>}
 *     Promise that resolves to the response
 */
proto.google.iam.v1beta.WorkloadIdentityPoolsPromiseClient.prototype.undeleteWorkloadIdentityPool =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/google.iam.v1beta.WorkloadIdentityPools/UndeleteWorkloadIdentityPool',
      request,
      metadata || {},
      methodDescriptor_WorkloadIdentityPools_UndeleteWorkloadIdentityPool);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.iam.v1beta.ListWorkloadIdentityPoolProvidersRequest,
 *   !proto.google.iam.v1beta.ListWorkloadIdentityPoolProvidersResponse>}
 */
const methodDescriptor_WorkloadIdentityPools_ListWorkloadIdentityPoolProviders = new grpc.web.MethodDescriptor(
  '/google.iam.v1beta.WorkloadIdentityPools/ListWorkloadIdentityPoolProviders',
  grpc.web.MethodType.UNARY,
  proto.google.iam.v1beta.ListWorkloadIdentityPoolProvidersRequest,
  proto.google.iam.v1beta.ListWorkloadIdentityPoolProvidersResponse,
  /**
   * @param {!proto.google.iam.v1beta.ListWorkloadIdentityPoolProvidersRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.google.iam.v1beta.ListWorkloadIdentityPoolProvidersResponse.deserializeBinary
);


/**
 * @param {!proto.google.iam.v1beta.ListWorkloadIdentityPoolProvidersRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.iam.v1beta.ListWorkloadIdentityPoolProvidersResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.iam.v1beta.ListWorkloadIdentityPoolProvidersResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.google.iam.v1beta.WorkloadIdentityPoolsClient.prototype.listWorkloadIdentityPoolProviders =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/google.iam.v1beta.WorkloadIdentityPools/ListWorkloadIdentityPoolProviders',
      request,
      metadata || {},
      methodDescriptor_WorkloadIdentityPools_ListWorkloadIdentityPoolProviders,
      callback);
};


/**
 * @param {!proto.google.iam.v1beta.ListWorkloadIdentityPoolProvidersRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.iam.v1beta.ListWorkloadIdentityPoolProvidersResponse>}
 *     Promise that resolves to the response
 */
proto.google.iam.v1beta.WorkloadIdentityPoolsPromiseClient.prototype.listWorkloadIdentityPoolProviders =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/google.iam.v1beta.WorkloadIdentityPools/ListWorkloadIdentityPoolProviders',
      request,
      metadata || {},
      methodDescriptor_WorkloadIdentityPools_ListWorkloadIdentityPoolProviders);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.iam.v1beta.GetWorkloadIdentityPoolProviderRequest,
 *   !proto.google.iam.v1beta.WorkloadIdentityPoolProvider>}
 */
const methodDescriptor_WorkloadIdentityPools_GetWorkloadIdentityPoolProvider = new grpc.web.MethodDescriptor(
  '/google.iam.v1beta.WorkloadIdentityPools/GetWorkloadIdentityPoolProvider',
  grpc.web.MethodType.UNARY,
  proto.google.iam.v1beta.GetWorkloadIdentityPoolProviderRequest,
  proto.google.iam.v1beta.WorkloadIdentityPoolProvider,
  /**
   * @param {!proto.google.iam.v1beta.GetWorkloadIdentityPoolProviderRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.google.iam.v1beta.WorkloadIdentityPoolProvider.deserializeBinary
);


/**
 * @param {!proto.google.iam.v1beta.GetWorkloadIdentityPoolProviderRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.iam.v1beta.WorkloadIdentityPoolProvider)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.iam.v1beta.WorkloadIdentityPoolProvider>|undefined}
 *     The XHR Node Readable Stream
 */
proto.google.iam.v1beta.WorkloadIdentityPoolsClient.prototype.getWorkloadIdentityPoolProvider =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/google.iam.v1beta.WorkloadIdentityPools/GetWorkloadIdentityPoolProvider',
      request,
      metadata || {},
      methodDescriptor_WorkloadIdentityPools_GetWorkloadIdentityPoolProvider,
      callback);
};


/**
 * @param {!proto.google.iam.v1beta.GetWorkloadIdentityPoolProviderRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.iam.v1beta.WorkloadIdentityPoolProvider>}
 *     Promise that resolves to the response
 */
proto.google.iam.v1beta.WorkloadIdentityPoolsPromiseClient.prototype.getWorkloadIdentityPoolProvider =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/google.iam.v1beta.WorkloadIdentityPools/GetWorkloadIdentityPoolProvider',
      request,
      metadata || {},
      methodDescriptor_WorkloadIdentityPools_GetWorkloadIdentityPoolProvider);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.iam.v1beta.CreateWorkloadIdentityPoolProviderRequest,
 *   !proto.google.longrunning.Operation>}
 */
const methodDescriptor_WorkloadIdentityPools_CreateWorkloadIdentityPoolProvider = new grpc.web.MethodDescriptor(
  '/google.iam.v1beta.WorkloadIdentityPools/CreateWorkloadIdentityPoolProvider',
  grpc.web.MethodType.UNARY,
  proto.google.iam.v1beta.CreateWorkloadIdentityPoolProviderRequest,
  google_longrunning_operations_pb.Operation,
  /**
   * @param {!proto.google.iam.v1beta.CreateWorkloadIdentityPoolProviderRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  google_longrunning_operations_pb.Operation.deserializeBinary
);


/**
 * @param {!proto.google.iam.v1beta.CreateWorkloadIdentityPoolProviderRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.longrunning.Operation)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.longrunning.Operation>|undefined}
 *     The XHR Node Readable Stream
 */
proto.google.iam.v1beta.WorkloadIdentityPoolsClient.prototype.createWorkloadIdentityPoolProvider =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/google.iam.v1beta.WorkloadIdentityPools/CreateWorkloadIdentityPoolProvider',
      request,
      metadata || {},
      methodDescriptor_WorkloadIdentityPools_CreateWorkloadIdentityPoolProvider,
      callback);
};


/**
 * @param {!proto.google.iam.v1beta.CreateWorkloadIdentityPoolProviderRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.longrunning.Operation>}
 *     Promise that resolves to the response
 */
proto.google.iam.v1beta.WorkloadIdentityPoolsPromiseClient.prototype.createWorkloadIdentityPoolProvider =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/google.iam.v1beta.WorkloadIdentityPools/CreateWorkloadIdentityPoolProvider',
      request,
      metadata || {},
      methodDescriptor_WorkloadIdentityPools_CreateWorkloadIdentityPoolProvider);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.iam.v1beta.UpdateWorkloadIdentityPoolProviderRequest,
 *   !proto.google.longrunning.Operation>}
 */
const methodDescriptor_WorkloadIdentityPools_UpdateWorkloadIdentityPoolProvider = new grpc.web.MethodDescriptor(
  '/google.iam.v1beta.WorkloadIdentityPools/UpdateWorkloadIdentityPoolProvider',
  grpc.web.MethodType.UNARY,
  proto.google.iam.v1beta.UpdateWorkloadIdentityPoolProviderRequest,
  google_longrunning_operations_pb.Operation,
  /**
   * @param {!proto.google.iam.v1beta.UpdateWorkloadIdentityPoolProviderRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  google_longrunning_operations_pb.Operation.deserializeBinary
);


/**
 * @param {!proto.google.iam.v1beta.UpdateWorkloadIdentityPoolProviderRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.longrunning.Operation)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.longrunning.Operation>|undefined}
 *     The XHR Node Readable Stream
 */
proto.google.iam.v1beta.WorkloadIdentityPoolsClient.prototype.updateWorkloadIdentityPoolProvider =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/google.iam.v1beta.WorkloadIdentityPools/UpdateWorkloadIdentityPoolProvider',
      request,
      metadata || {},
      methodDescriptor_WorkloadIdentityPools_UpdateWorkloadIdentityPoolProvider,
      callback);
};


/**
 * @param {!proto.google.iam.v1beta.UpdateWorkloadIdentityPoolProviderRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.longrunning.Operation>}
 *     Promise that resolves to the response
 */
proto.google.iam.v1beta.WorkloadIdentityPoolsPromiseClient.prototype.updateWorkloadIdentityPoolProvider =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/google.iam.v1beta.WorkloadIdentityPools/UpdateWorkloadIdentityPoolProvider',
      request,
      metadata || {},
      methodDescriptor_WorkloadIdentityPools_UpdateWorkloadIdentityPoolProvider);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.iam.v1beta.DeleteWorkloadIdentityPoolProviderRequest,
 *   !proto.google.longrunning.Operation>}
 */
const methodDescriptor_WorkloadIdentityPools_DeleteWorkloadIdentityPoolProvider = new grpc.web.MethodDescriptor(
  '/google.iam.v1beta.WorkloadIdentityPools/DeleteWorkloadIdentityPoolProvider',
  grpc.web.MethodType.UNARY,
  proto.google.iam.v1beta.DeleteWorkloadIdentityPoolProviderRequest,
  google_longrunning_operations_pb.Operation,
  /**
   * @param {!proto.google.iam.v1beta.DeleteWorkloadIdentityPoolProviderRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  google_longrunning_operations_pb.Operation.deserializeBinary
);


/**
 * @param {!proto.google.iam.v1beta.DeleteWorkloadIdentityPoolProviderRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.longrunning.Operation)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.longrunning.Operation>|undefined}
 *     The XHR Node Readable Stream
 */
proto.google.iam.v1beta.WorkloadIdentityPoolsClient.prototype.deleteWorkloadIdentityPoolProvider =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/google.iam.v1beta.WorkloadIdentityPools/DeleteWorkloadIdentityPoolProvider',
      request,
      metadata || {},
      methodDescriptor_WorkloadIdentityPools_DeleteWorkloadIdentityPoolProvider,
      callback);
};


/**
 * @param {!proto.google.iam.v1beta.DeleteWorkloadIdentityPoolProviderRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.longrunning.Operation>}
 *     Promise that resolves to the response
 */
proto.google.iam.v1beta.WorkloadIdentityPoolsPromiseClient.prototype.deleteWorkloadIdentityPoolProvider =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/google.iam.v1beta.WorkloadIdentityPools/DeleteWorkloadIdentityPoolProvider',
      request,
      metadata || {},
      methodDescriptor_WorkloadIdentityPools_DeleteWorkloadIdentityPoolProvider);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.iam.v1beta.UndeleteWorkloadIdentityPoolProviderRequest,
 *   !proto.google.longrunning.Operation>}
 */
const methodDescriptor_WorkloadIdentityPools_UndeleteWorkloadIdentityPoolProvider = new grpc.web.MethodDescriptor(
  '/google.iam.v1beta.WorkloadIdentityPools/UndeleteWorkloadIdentityPoolProvider',
  grpc.web.MethodType.UNARY,
  proto.google.iam.v1beta.UndeleteWorkloadIdentityPoolProviderRequest,
  google_longrunning_operations_pb.Operation,
  /**
   * @param {!proto.google.iam.v1beta.UndeleteWorkloadIdentityPoolProviderRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  google_longrunning_operations_pb.Operation.deserializeBinary
);


/**
 * @param {!proto.google.iam.v1beta.UndeleteWorkloadIdentityPoolProviderRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.longrunning.Operation)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.longrunning.Operation>|undefined}
 *     The XHR Node Readable Stream
 */
proto.google.iam.v1beta.WorkloadIdentityPoolsClient.prototype.undeleteWorkloadIdentityPoolProvider =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/google.iam.v1beta.WorkloadIdentityPools/UndeleteWorkloadIdentityPoolProvider',
      request,
      metadata || {},
      methodDescriptor_WorkloadIdentityPools_UndeleteWorkloadIdentityPoolProvider,
      callback);
};


/**
 * @param {!proto.google.iam.v1beta.UndeleteWorkloadIdentityPoolProviderRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.longrunning.Operation>}
 *     Promise that resolves to the response
 */
proto.google.iam.v1beta.WorkloadIdentityPoolsPromiseClient.prototype.undeleteWorkloadIdentityPoolProvider =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/google.iam.v1beta.WorkloadIdentityPools/UndeleteWorkloadIdentityPoolProvider',
      request,
      metadata || {},
      methodDescriptor_WorkloadIdentityPools_UndeleteWorkloadIdentityPoolProvider);
};


module.exports = proto.google.iam.v1beta;

