/**
 * @fileoverview gRPC-Web generated client stub for google.iam.v2
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.1
// 	protoc              v3.19.1
// source: google/iam/v2/policy.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var google_api_annotations_pb = require('../../../google/api/annotations_pb.js')

var google_api_client_pb = require('../../../google/api/client_pb.js')

var google_api_field_behavior_pb = require('../../../google/api/field_behavior_pb.js')

var google_iam_v2_deny_pb = require('../../../google/iam/v2/deny_pb.js')

var google_longrunning_operations_pb = require('../../../google/longrunning/operations_pb.js')

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js')
const proto = {};
proto.google = {};
proto.google.iam = {};
proto.google.iam.v2 = require('./policy_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.google.iam.v2.PoliciesClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.google.iam.v2.PoliciesPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.iam.v2.ListPoliciesRequest,
 *   !proto.google.iam.v2.ListPoliciesResponse>}
 */
const methodDescriptor_Policies_ListPolicies = new grpc.web.MethodDescriptor(
  '/google.iam.v2.Policies/ListPolicies',
  grpc.web.MethodType.UNARY,
  proto.google.iam.v2.ListPoliciesRequest,
  proto.google.iam.v2.ListPoliciesResponse,
  /**
   * @param {!proto.google.iam.v2.ListPoliciesRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.google.iam.v2.ListPoliciesResponse.deserializeBinary
);


/**
 * @param {!proto.google.iam.v2.ListPoliciesRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.iam.v2.ListPoliciesResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.iam.v2.ListPoliciesResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.google.iam.v2.PoliciesClient.prototype.listPolicies =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/google.iam.v2.Policies/ListPolicies',
      request,
      metadata || {},
      methodDescriptor_Policies_ListPolicies,
      callback);
};


/**
 * @param {!proto.google.iam.v2.ListPoliciesRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.iam.v2.ListPoliciesResponse>}
 *     Promise that resolves to the response
 */
proto.google.iam.v2.PoliciesPromiseClient.prototype.listPolicies =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/google.iam.v2.Policies/ListPolicies',
      request,
      metadata || {},
      methodDescriptor_Policies_ListPolicies);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.iam.v2.GetPolicyRequest,
 *   !proto.google.iam.v2.Policy>}
 */
const methodDescriptor_Policies_GetPolicy = new grpc.web.MethodDescriptor(
  '/google.iam.v2.Policies/GetPolicy',
  grpc.web.MethodType.UNARY,
  proto.google.iam.v2.GetPolicyRequest,
  proto.google.iam.v2.Policy,
  /**
   * @param {!proto.google.iam.v2.GetPolicyRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.google.iam.v2.Policy.deserializeBinary
);


/**
 * @param {!proto.google.iam.v2.GetPolicyRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.iam.v2.Policy)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.iam.v2.Policy>|undefined}
 *     The XHR Node Readable Stream
 */
proto.google.iam.v2.PoliciesClient.prototype.getPolicy =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/google.iam.v2.Policies/GetPolicy',
      request,
      metadata || {},
      methodDescriptor_Policies_GetPolicy,
      callback);
};


/**
 * @param {!proto.google.iam.v2.GetPolicyRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.iam.v2.Policy>}
 *     Promise that resolves to the response
 */
proto.google.iam.v2.PoliciesPromiseClient.prototype.getPolicy =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/google.iam.v2.Policies/GetPolicy',
      request,
      metadata || {},
      methodDescriptor_Policies_GetPolicy);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.iam.v2.CreatePolicyRequest,
 *   !proto.google.longrunning.Operation>}
 */
const methodDescriptor_Policies_CreatePolicy = new grpc.web.MethodDescriptor(
  '/google.iam.v2.Policies/CreatePolicy',
  grpc.web.MethodType.UNARY,
  proto.google.iam.v2.CreatePolicyRequest,
  google_longrunning_operations_pb.Operation,
  /**
   * @param {!proto.google.iam.v2.CreatePolicyRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  google_longrunning_operations_pb.Operation.deserializeBinary
);


/**
 * @param {!proto.google.iam.v2.CreatePolicyRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.longrunning.Operation)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.longrunning.Operation>|undefined}
 *     The XHR Node Readable Stream
 */
proto.google.iam.v2.PoliciesClient.prototype.createPolicy =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/google.iam.v2.Policies/CreatePolicy',
      request,
      metadata || {},
      methodDescriptor_Policies_CreatePolicy,
      callback);
};


/**
 * @param {!proto.google.iam.v2.CreatePolicyRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.longrunning.Operation>}
 *     Promise that resolves to the response
 */
proto.google.iam.v2.PoliciesPromiseClient.prototype.createPolicy =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/google.iam.v2.Policies/CreatePolicy',
      request,
      metadata || {},
      methodDescriptor_Policies_CreatePolicy);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.iam.v2.UpdatePolicyRequest,
 *   !proto.google.longrunning.Operation>}
 */
const methodDescriptor_Policies_UpdatePolicy = new grpc.web.MethodDescriptor(
  '/google.iam.v2.Policies/UpdatePolicy',
  grpc.web.MethodType.UNARY,
  proto.google.iam.v2.UpdatePolicyRequest,
  google_longrunning_operations_pb.Operation,
  /**
   * @param {!proto.google.iam.v2.UpdatePolicyRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  google_longrunning_operations_pb.Operation.deserializeBinary
);


/**
 * @param {!proto.google.iam.v2.UpdatePolicyRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.longrunning.Operation)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.longrunning.Operation>|undefined}
 *     The XHR Node Readable Stream
 */
proto.google.iam.v2.PoliciesClient.prototype.updatePolicy =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/google.iam.v2.Policies/UpdatePolicy',
      request,
      metadata || {},
      methodDescriptor_Policies_UpdatePolicy,
      callback);
};


/**
 * @param {!proto.google.iam.v2.UpdatePolicyRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.longrunning.Operation>}
 *     Promise that resolves to the response
 */
proto.google.iam.v2.PoliciesPromiseClient.prototype.updatePolicy =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/google.iam.v2.Policies/UpdatePolicy',
      request,
      metadata || {},
      methodDescriptor_Policies_UpdatePolicy);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.iam.v2.DeletePolicyRequest,
 *   !proto.google.longrunning.Operation>}
 */
const methodDescriptor_Policies_DeletePolicy = new grpc.web.MethodDescriptor(
  '/google.iam.v2.Policies/DeletePolicy',
  grpc.web.MethodType.UNARY,
  proto.google.iam.v2.DeletePolicyRequest,
  google_longrunning_operations_pb.Operation,
  /**
   * @param {!proto.google.iam.v2.DeletePolicyRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  google_longrunning_operations_pb.Operation.deserializeBinary
);


/**
 * @param {!proto.google.iam.v2.DeletePolicyRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.longrunning.Operation)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.longrunning.Operation>|undefined}
 *     The XHR Node Readable Stream
 */
proto.google.iam.v2.PoliciesClient.prototype.deletePolicy =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/google.iam.v2.Policies/DeletePolicy',
      request,
      metadata || {},
      methodDescriptor_Policies_DeletePolicy,
      callback);
};


/**
 * @param {!proto.google.iam.v2.DeletePolicyRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.longrunning.Operation>}
 *     Promise that resolves to the response
 */
proto.google.iam.v2.PoliciesPromiseClient.prototype.deletePolicy =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/google.iam.v2.Policies/DeletePolicy',
      request,
      metadata || {},
      methodDescriptor_Policies_DeletePolicy);
};


module.exports = proto.google.iam.v2;

