/**
 * @fileoverview gRPC-Web generated client stub for google.api.apikeys.v2
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.1
// 	protoc              v3.19.1
// source: google/api/apikeys/v2/apikeys.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var google_api_annotations_pb = require('../../../../google/api/annotations_pb.js')

var google_api_apikeys_v2_resources_pb = require('../../../../google/api/apikeys/v2/resources_pb.js')

var google_api_client_pb = require('../../../../google/api/client_pb.js')

var google_api_field_behavior_pb = require('../../../../google/api/field_behavior_pb.js')

var google_api_resource_pb = require('../../../../google/api/resource_pb.js')

var google_longrunning_operations_pb = require('../../../../google/longrunning/operations_pb.js')

var google_protobuf_field_mask_pb = require('google-protobuf/google/protobuf/field_mask_pb.js')
const proto = {};
proto.google = {};
proto.google.api = {};
proto.google.api.apikeys = {};
proto.google.api.apikeys.v2 = require('./apikeys_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.google.api.apikeys.v2.ApiKeysClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.google.api.apikeys.v2.ApiKeysPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.api.apikeys.v2.CreateKeyRequest,
 *   !proto.google.longrunning.Operation>}
 */
const methodDescriptor_ApiKeys_CreateKey = new grpc.web.MethodDescriptor(
  '/google.api.apikeys.v2.ApiKeys/CreateKey',
  grpc.web.MethodType.UNARY,
  proto.google.api.apikeys.v2.CreateKeyRequest,
  google_longrunning_operations_pb.Operation,
  /**
   * @param {!proto.google.api.apikeys.v2.CreateKeyRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  google_longrunning_operations_pb.Operation.deserializeBinary
);


/**
 * @param {!proto.google.api.apikeys.v2.CreateKeyRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.longrunning.Operation)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.longrunning.Operation>|undefined}
 *     The XHR Node Readable Stream
 */
proto.google.api.apikeys.v2.ApiKeysClient.prototype.createKey =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/google.api.apikeys.v2.ApiKeys/CreateKey',
      request,
      metadata || {},
      methodDescriptor_ApiKeys_CreateKey,
      callback);
};


/**
 * @param {!proto.google.api.apikeys.v2.CreateKeyRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.longrunning.Operation>}
 *     Promise that resolves to the response
 */
proto.google.api.apikeys.v2.ApiKeysPromiseClient.prototype.createKey =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/google.api.apikeys.v2.ApiKeys/CreateKey',
      request,
      metadata || {},
      methodDescriptor_ApiKeys_CreateKey);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.api.apikeys.v2.ListKeysRequest,
 *   !proto.google.api.apikeys.v2.ListKeysResponse>}
 */
const methodDescriptor_ApiKeys_ListKeys = new grpc.web.MethodDescriptor(
  '/google.api.apikeys.v2.ApiKeys/ListKeys',
  grpc.web.MethodType.UNARY,
  proto.google.api.apikeys.v2.ListKeysRequest,
  proto.google.api.apikeys.v2.ListKeysResponse,
  /**
   * @param {!proto.google.api.apikeys.v2.ListKeysRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.google.api.apikeys.v2.ListKeysResponse.deserializeBinary
);


/**
 * @param {!proto.google.api.apikeys.v2.ListKeysRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.api.apikeys.v2.ListKeysResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.api.apikeys.v2.ListKeysResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.google.api.apikeys.v2.ApiKeysClient.prototype.listKeys =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/google.api.apikeys.v2.ApiKeys/ListKeys',
      request,
      metadata || {},
      methodDescriptor_ApiKeys_ListKeys,
      callback);
};


/**
 * @param {!proto.google.api.apikeys.v2.ListKeysRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.api.apikeys.v2.ListKeysResponse>}
 *     Promise that resolves to the response
 */
proto.google.api.apikeys.v2.ApiKeysPromiseClient.prototype.listKeys =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/google.api.apikeys.v2.ApiKeys/ListKeys',
      request,
      metadata || {},
      methodDescriptor_ApiKeys_ListKeys);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.api.apikeys.v2.GetKeyRequest,
 *   !proto.google.api.apikeys.v2.Key>}
 */
const methodDescriptor_ApiKeys_GetKey = new grpc.web.MethodDescriptor(
  '/google.api.apikeys.v2.ApiKeys/GetKey',
  grpc.web.MethodType.UNARY,
  proto.google.api.apikeys.v2.GetKeyRequest,
  google_api_apikeys_v2_resources_pb.Key,
  /**
   * @param {!proto.google.api.apikeys.v2.GetKeyRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  google_api_apikeys_v2_resources_pb.Key.deserializeBinary
);


/**
 * @param {!proto.google.api.apikeys.v2.GetKeyRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.api.apikeys.v2.Key)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.api.apikeys.v2.Key>|undefined}
 *     The XHR Node Readable Stream
 */
proto.google.api.apikeys.v2.ApiKeysClient.prototype.getKey =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/google.api.apikeys.v2.ApiKeys/GetKey',
      request,
      metadata || {},
      methodDescriptor_ApiKeys_GetKey,
      callback);
};


/**
 * @param {!proto.google.api.apikeys.v2.GetKeyRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.api.apikeys.v2.Key>}
 *     Promise that resolves to the response
 */
proto.google.api.apikeys.v2.ApiKeysPromiseClient.prototype.getKey =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/google.api.apikeys.v2.ApiKeys/GetKey',
      request,
      metadata || {},
      methodDescriptor_ApiKeys_GetKey);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.api.apikeys.v2.GetKeyStringRequest,
 *   !proto.google.api.apikeys.v2.GetKeyStringResponse>}
 */
const methodDescriptor_ApiKeys_GetKeyString = new grpc.web.MethodDescriptor(
  '/google.api.apikeys.v2.ApiKeys/GetKeyString',
  grpc.web.MethodType.UNARY,
  proto.google.api.apikeys.v2.GetKeyStringRequest,
  proto.google.api.apikeys.v2.GetKeyStringResponse,
  /**
   * @param {!proto.google.api.apikeys.v2.GetKeyStringRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.google.api.apikeys.v2.GetKeyStringResponse.deserializeBinary
);


/**
 * @param {!proto.google.api.apikeys.v2.GetKeyStringRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.api.apikeys.v2.GetKeyStringResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.api.apikeys.v2.GetKeyStringResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.google.api.apikeys.v2.ApiKeysClient.prototype.getKeyString =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/google.api.apikeys.v2.ApiKeys/GetKeyString',
      request,
      metadata || {},
      methodDescriptor_ApiKeys_GetKeyString,
      callback);
};


/**
 * @param {!proto.google.api.apikeys.v2.GetKeyStringRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.api.apikeys.v2.GetKeyStringResponse>}
 *     Promise that resolves to the response
 */
proto.google.api.apikeys.v2.ApiKeysPromiseClient.prototype.getKeyString =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/google.api.apikeys.v2.ApiKeys/GetKeyString',
      request,
      metadata || {},
      methodDescriptor_ApiKeys_GetKeyString);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.api.apikeys.v2.UpdateKeyRequest,
 *   !proto.google.longrunning.Operation>}
 */
const methodDescriptor_ApiKeys_UpdateKey = new grpc.web.MethodDescriptor(
  '/google.api.apikeys.v2.ApiKeys/UpdateKey',
  grpc.web.MethodType.UNARY,
  proto.google.api.apikeys.v2.UpdateKeyRequest,
  google_longrunning_operations_pb.Operation,
  /**
   * @param {!proto.google.api.apikeys.v2.UpdateKeyRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  google_longrunning_operations_pb.Operation.deserializeBinary
);


/**
 * @param {!proto.google.api.apikeys.v2.UpdateKeyRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.longrunning.Operation)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.longrunning.Operation>|undefined}
 *     The XHR Node Readable Stream
 */
proto.google.api.apikeys.v2.ApiKeysClient.prototype.updateKey =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/google.api.apikeys.v2.ApiKeys/UpdateKey',
      request,
      metadata || {},
      methodDescriptor_ApiKeys_UpdateKey,
      callback);
};


/**
 * @param {!proto.google.api.apikeys.v2.UpdateKeyRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.longrunning.Operation>}
 *     Promise that resolves to the response
 */
proto.google.api.apikeys.v2.ApiKeysPromiseClient.prototype.updateKey =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/google.api.apikeys.v2.ApiKeys/UpdateKey',
      request,
      metadata || {},
      methodDescriptor_ApiKeys_UpdateKey);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.api.apikeys.v2.DeleteKeyRequest,
 *   !proto.google.longrunning.Operation>}
 */
const methodDescriptor_ApiKeys_DeleteKey = new grpc.web.MethodDescriptor(
  '/google.api.apikeys.v2.ApiKeys/DeleteKey',
  grpc.web.MethodType.UNARY,
  proto.google.api.apikeys.v2.DeleteKeyRequest,
  google_longrunning_operations_pb.Operation,
  /**
   * @param {!proto.google.api.apikeys.v2.DeleteKeyRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  google_longrunning_operations_pb.Operation.deserializeBinary
);


/**
 * @param {!proto.google.api.apikeys.v2.DeleteKeyRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.longrunning.Operation)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.longrunning.Operation>|undefined}
 *     The XHR Node Readable Stream
 */
proto.google.api.apikeys.v2.ApiKeysClient.prototype.deleteKey =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/google.api.apikeys.v2.ApiKeys/DeleteKey',
      request,
      metadata || {},
      methodDescriptor_ApiKeys_DeleteKey,
      callback);
};


/**
 * @param {!proto.google.api.apikeys.v2.DeleteKeyRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.longrunning.Operation>}
 *     Promise that resolves to the response
 */
proto.google.api.apikeys.v2.ApiKeysPromiseClient.prototype.deleteKey =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/google.api.apikeys.v2.ApiKeys/DeleteKey',
      request,
      metadata || {},
      methodDescriptor_ApiKeys_DeleteKey);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.api.apikeys.v2.UndeleteKeyRequest,
 *   !proto.google.longrunning.Operation>}
 */
const methodDescriptor_ApiKeys_UndeleteKey = new grpc.web.MethodDescriptor(
  '/google.api.apikeys.v2.ApiKeys/UndeleteKey',
  grpc.web.MethodType.UNARY,
  proto.google.api.apikeys.v2.UndeleteKeyRequest,
  google_longrunning_operations_pb.Operation,
  /**
   * @param {!proto.google.api.apikeys.v2.UndeleteKeyRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  google_longrunning_operations_pb.Operation.deserializeBinary
);


/**
 * @param {!proto.google.api.apikeys.v2.UndeleteKeyRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.longrunning.Operation)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.longrunning.Operation>|undefined}
 *     The XHR Node Readable Stream
 */
proto.google.api.apikeys.v2.ApiKeysClient.prototype.undeleteKey =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/google.api.apikeys.v2.ApiKeys/UndeleteKey',
      request,
      metadata || {},
      methodDescriptor_ApiKeys_UndeleteKey,
      callback);
};


/**
 * @param {!proto.google.api.apikeys.v2.UndeleteKeyRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.longrunning.Operation>}
 *     Promise that resolves to the response
 */
proto.google.api.apikeys.v2.ApiKeysPromiseClient.prototype.undeleteKey =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/google.api.apikeys.v2.ApiKeys/UndeleteKey',
      request,
      metadata || {},
      methodDescriptor_ApiKeys_UndeleteKey);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.api.apikeys.v2.LookupKeyRequest,
 *   !proto.google.api.apikeys.v2.LookupKeyResponse>}
 */
const methodDescriptor_ApiKeys_LookupKey = new grpc.web.MethodDescriptor(
  '/google.api.apikeys.v2.ApiKeys/LookupKey',
  grpc.web.MethodType.UNARY,
  proto.google.api.apikeys.v2.LookupKeyRequest,
  proto.google.api.apikeys.v2.LookupKeyResponse,
  /**
   * @param {!proto.google.api.apikeys.v2.LookupKeyRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.google.api.apikeys.v2.LookupKeyResponse.deserializeBinary
);


/**
 * @param {!proto.google.api.apikeys.v2.LookupKeyRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.api.apikeys.v2.LookupKeyResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.api.apikeys.v2.LookupKeyResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.google.api.apikeys.v2.ApiKeysClient.prototype.lookupKey =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/google.api.apikeys.v2.ApiKeys/LookupKey',
      request,
      metadata || {},
      methodDescriptor_ApiKeys_LookupKey,
      callback);
};


/**
 * @param {!proto.google.api.apikeys.v2.LookupKeyRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.api.apikeys.v2.LookupKeyResponse>}
 *     Promise that resolves to the response
 */
proto.google.api.apikeys.v2.ApiKeysPromiseClient.prototype.lookupKey =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/google.api.apikeys.v2.ApiKeys/LookupKey',
      request,
      metadata || {},
      methodDescriptor_ApiKeys_LookupKey);
};


module.exports = proto.google.api.apikeys.v2;

