// source: google/api/apikeys/v2/resources.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

var google_api_field_behavior_pb = require('../../../../google/api/field_behavior_pb.js');
goog.object.extend(proto, google_api_field_behavior_pb);
var google_api_resource_pb = require('../../../../google/api/resource_pb.js');
goog.object.extend(proto, google_api_resource_pb);
var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
goog.exportSymbol('proto.google.api.apikeys.v2.AndroidApplication', null, global);
goog.exportSymbol('proto.google.api.apikeys.v2.AndroidKeyRestrictions', null, global);
goog.exportSymbol('proto.google.api.apikeys.v2.ApiTarget', null, global);
goog.exportSymbol('proto.google.api.apikeys.v2.BrowserKeyRestrictions', null, global);
goog.exportSymbol('proto.google.api.apikeys.v2.IosKeyRestrictions', null, global);
goog.exportSymbol('proto.google.api.apikeys.v2.Key', null, global);
goog.exportSymbol('proto.google.api.apikeys.v2.Restrictions', null, global);
goog.exportSymbol('proto.google.api.apikeys.v2.Restrictions.ClientRestrictionsCase', null, global);
goog.exportSymbol('proto.google.api.apikeys.v2.ServerKeyRestrictions', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.api.apikeys.v2.Key = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.api.apikeys.v2.Key, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.api.apikeys.v2.Key.displayName = 'proto.google.api.apikeys.v2.Key';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.api.apikeys.v2.Restrictions = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.google.api.apikeys.v2.Restrictions.repeatedFields_, proto.google.api.apikeys.v2.Restrictions.oneofGroups_);
};
goog.inherits(proto.google.api.apikeys.v2.Restrictions, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.api.apikeys.v2.Restrictions.displayName = 'proto.google.api.apikeys.v2.Restrictions';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.api.apikeys.v2.BrowserKeyRestrictions = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.google.api.apikeys.v2.BrowserKeyRestrictions.repeatedFields_, null);
};
goog.inherits(proto.google.api.apikeys.v2.BrowserKeyRestrictions, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.api.apikeys.v2.BrowserKeyRestrictions.displayName = 'proto.google.api.apikeys.v2.BrowserKeyRestrictions';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.api.apikeys.v2.ServerKeyRestrictions = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.google.api.apikeys.v2.ServerKeyRestrictions.repeatedFields_, null);
};
goog.inherits(proto.google.api.apikeys.v2.ServerKeyRestrictions, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.api.apikeys.v2.ServerKeyRestrictions.displayName = 'proto.google.api.apikeys.v2.ServerKeyRestrictions';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.api.apikeys.v2.AndroidKeyRestrictions = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.google.api.apikeys.v2.AndroidKeyRestrictions.repeatedFields_, null);
};
goog.inherits(proto.google.api.apikeys.v2.AndroidKeyRestrictions, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.api.apikeys.v2.AndroidKeyRestrictions.displayName = 'proto.google.api.apikeys.v2.AndroidKeyRestrictions';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.api.apikeys.v2.AndroidApplication = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.api.apikeys.v2.AndroidApplication, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.api.apikeys.v2.AndroidApplication.displayName = 'proto.google.api.apikeys.v2.AndroidApplication';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.api.apikeys.v2.IosKeyRestrictions = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.google.api.apikeys.v2.IosKeyRestrictions.repeatedFields_, null);
};
goog.inherits(proto.google.api.apikeys.v2.IosKeyRestrictions, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.api.apikeys.v2.IosKeyRestrictions.displayName = 'proto.google.api.apikeys.v2.IosKeyRestrictions';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.api.apikeys.v2.ApiTarget = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.google.api.apikeys.v2.ApiTarget.repeatedFields_, null);
};
goog.inherits(proto.google.api.apikeys.v2.ApiTarget, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.api.apikeys.v2.ApiTarget.displayName = 'proto.google.api.apikeys.v2.ApiTarget';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.api.apikeys.v2.Key.prototype.toObject = function(opt_includeInstance) {
  return proto.google.api.apikeys.v2.Key.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.api.apikeys.v2.Key} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.api.apikeys.v2.Key.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    uid: jspb.Message.getFieldWithDefault(msg, 5, ""),
    displayName: jspb.Message.getFieldWithDefault(msg, 2, ""),
    keyString: jspb.Message.getFieldWithDefault(msg, 3, ""),
    createTime: (f = msg.getCreateTime()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    updateTime: (f = msg.getUpdateTime()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    deleteTime: (f = msg.getDeleteTime()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    annotationsMap: (f = msg.getAnnotationsMap()) ? f.toObject(includeInstance, undefined) : [],
    restrictions: (f = msg.getRestrictions()) && proto.google.api.apikeys.v2.Restrictions.toObject(includeInstance, f),
    etag: jspb.Message.getFieldWithDefault(msg, 11, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.api.apikeys.v2.Key}
 */
proto.google.api.apikeys.v2.Key.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.api.apikeys.v2.Key;
  return proto.google.api.apikeys.v2.Key.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.api.apikeys.v2.Key} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.api.apikeys.v2.Key}
 */
proto.google.api.apikeys.v2.Key.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setUid(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setDisplayName(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setKeyString(value);
      break;
    case 4:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setCreateTime(value);
      break;
    case 6:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setUpdateTime(value);
      break;
    case 7:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setDeleteTime(value);
      break;
    case 8:
      var value = msg.getAnnotationsMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString, null, "", "");
         });
      break;
    case 9:
      var value = new proto.google.api.apikeys.v2.Restrictions;
      reader.readMessage(value,proto.google.api.apikeys.v2.Restrictions.deserializeBinaryFromReader);
      msg.setRestrictions(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.setEtag(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.api.apikeys.v2.Key.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.api.apikeys.v2.Key.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.api.apikeys.v2.Key} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.api.apikeys.v2.Key.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getUid();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getDisplayName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getKeyString();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getCreateTime();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getUpdateTime();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getDeleteTime();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getAnnotationsMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(8, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
  f = message.getRestrictions();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      proto.google.api.apikeys.v2.Restrictions.serializeBinaryToWriter
    );
  }
  f = message.getEtag();
  if (f.length > 0) {
    writer.writeString(
      11,
      f
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.google.api.apikeys.v2.Key.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.api.apikeys.v2.Key} returns this
 */
proto.google.api.apikeys.v2.Key.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string uid = 5;
 * @return {string}
 */
proto.google.api.apikeys.v2.Key.prototype.getUid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.api.apikeys.v2.Key} returns this
 */
proto.google.api.apikeys.v2.Key.prototype.setUid = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string display_name = 2;
 * @return {string}
 */
proto.google.api.apikeys.v2.Key.prototype.getDisplayName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.api.apikeys.v2.Key} returns this
 */
proto.google.api.apikeys.v2.Key.prototype.setDisplayName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string key_string = 3;
 * @return {string}
 */
proto.google.api.apikeys.v2.Key.prototype.getKeyString = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.api.apikeys.v2.Key} returns this
 */
proto.google.api.apikeys.v2.Key.prototype.setKeyString = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional google.protobuf.Timestamp create_time = 4;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.google.api.apikeys.v2.Key.prototype.getCreateTime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 4));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.google.api.apikeys.v2.Key} returns this
*/
proto.google.api.apikeys.v2.Key.prototype.setCreateTime = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.api.apikeys.v2.Key} returns this
 */
proto.google.api.apikeys.v2.Key.prototype.clearCreateTime = function() {
  return this.setCreateTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.api.apikeys.v2.Key.prototype.hasCreateTime = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional google.protobuf.Timestamp update_time = 6;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.google.api.apikeys.v2.Key.prototype.getUpdateTime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 6));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.google.api.apikeys.v2.Key} returns this
*/
proto.google.api.apikeys.v2.Key.prototype.setUpdateTime = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.api.apikeys.v2.Key} returns this
 */
proto.google.api.apikeys.v2.Key.prototype.clearUpdateTime = function() {
  return this.setUpdateTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.api.apikeys.v2.Key.prototype.hasUpdateTime = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional google.protobuf.Timestamp delete_time = 7;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.google.api.apikeys.v2.Key.prototype.getDeleteTime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 7));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.google.api.apikeys.v2.Key} returns this
*/
proto.google.api.apikeys.v2.Key.prototype.setDeleteTime = function(value) {
  return jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.api.apikeys.v2.Key} returns this
 */
proto.google.api.apikeys.v2.Key.prototype.clearDeleteTime = function() {
  return this.setDeleteTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.api.apikeys.v2.Key.prototype.hasDeleteTime = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * map<string, string> annotations = 8;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.google.api.apikeys.v2.Key.prototype.getAnnotationsMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 8, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.google.api.apikeys.v2.Key} returns this
 */
proto.google.api.apikeys.v2.Key.prototype.clearAnnotationsMap = function() {
  this.getAnnotationsMap().clear();
  return this;};


/**
 * optional Restrictions restrictions = 9;
 * @return {?proto.google.api.apikeys.v2.Restrictions}
 */
proto.google.api.apikeys.v2.Key.prototype.getRestrictions = function() {
  return /** @type{?proto.google.api.apikeys.v2.Restrictions} */ (
    jspb.Message.getWrapperField(this, proto.google.api.apikeys.v2.Restrictions, 9));
};


/**
 * @param {?proto.google.api.apikeys.v2.Restrictions|undefined} value
 * @return {!proto.google.api.apikeys.v2.Key} returns this
*/
proto.google.api.apikeys.v2.Key.prototype.setRestrictions = function(value) {
  return jspb.Message.setWrapperField(this, 9, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.api.apikeys.v2.Key} returns this
 */
proto.google.api.apikeys.v2.Key.prototype.clearRestrictions = function() {
  return this.setRestrictions(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.api.apikeys.v2.Key.prototype.hasRestrictions = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional string etag = 11;
 * @return {string}
 */
proto.google.api.apikeys.v2.Key.prototype.getEtag = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 11, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.api.apikeys.v2.Key} returns this
 */
proto.google.api.apikeys.v2.Key.prototype.setEtag = function(value) {
  return jspb.Message.setProto3StringField(this, 11, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.google.api.apikeys.v2.Restrictions.repeatedFields_ = [5];

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.google.api.apikeys.v2.Restrictions.oneofGroups_ = [[1,2,3,4]];

/**
 * @enum {number}
 */
proto.google.api.apikeys.v2.Restrictions.ClientRestrictionsCase = {
  CLIENT_RESTRICTIONS_NOT_SET: 0,
  BROWSER_KEY_RESTRICTIONS: 1,
  SERVER_KEY_RESTRICTIONS: 2,
  ANDROID_KEY_RESTRICTIONS: 3,
  IOS_KEY_RESTRICTIONS: 4
};

/**
 * @return {proto.google.api.apikeys.v2.Restrictions.ClientRestrictionsCase}
 */
proto.google.api.apikeys.v2.Restrictions.prototype.getClientRestrictionsCase = function() {
  return /** @type {proto.google.api.apikeys.v2.Restrictions.ClientRestrictionsCase} */(jspb.Message.computeOneofCase(this, proto.google.api.apikeys.v2.Restrictions.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.api.apikeys.v2.Restrictions.prototype.toObject = function(opt_includeInstance) {
  return proto.google.api.apikeys.v2.Restrictions.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.api.apikeys.v2.Restrictions} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.api.apikeys.v2.Restrictions.toObject = function(includeInstance, msg) {
  var f, obj = {
    browserKeyRestrictions: (f = msg.getBrowserKeyRestrictions()) && proto.google.api.apikeys.v2.BrowserKeyRestrictions.toObject(includeInstance, f),
    serverKeyRestrictions: (f = msg.getServerKeyRestrictions()) && proto.google.api.apikeys.v2.ServerKeyRestrictions.toObject(includeInstance, f),
    androidKeyRestrictions: (f = msg.getAndroidKeyRestrictions()) && proto.google.api.apikeys.v2.AndroidKeyRestrictions.toObject(includeInstance, f),
    iosKeyRestrictions: (f = msg.getIosKeyRestrictions()) && proto.google.api.apikeys.v2.IosKeyRestrictions.toObject(includeInstance, f),
    apiTargetsList: jspb.Message.toObjectList(msg.getApiTargetsList(),
    proto.google.api.apikeys.v2.ApiTarget.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.api.apikeys.v2.Restrictions}
 */
proto.google.api.apikeys.v2.Restrictions.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.api.apikeys.v2.Restrictions;
  return proto.google.api.apikeys.v2.Restrictions.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.api.apikeys.v2.Restrictions} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.api.apikeys.v2.Restrictions}
 */
proto.google.api.apikeys.v2.Restrictions.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.google.api.apikeys.v2.BrowserKeyRestrictions;
      reader.readMessage(value,proto.google.api.apikeys.v2.BrowserKeyRestrictions.deserializeBinaryFromReader);
      msg.setBrowserKeyRestrictions(value);
      break;
    case 2:
      var value = new proto.google.api.apikeys.v2.ServerKeyRestrictions;
      reader.readMessage(value,proto.google.api.apikeys.v2.ServerKeyRestrictions.deserializeBinaryFromReader);
      msg.setServerKeyRestrictions(value);
      break;
    case 3:
      var value = new proto.google.api.apikeys.v2.AndroidKeyRestrictions;
      reader.readMessage(value,proto.google.api.apikeys.v2.AndroidKeyRestrictions.deserializeBinaryFromReader);
      msg.setAndroidKeyRestrictions(value);
      break;
    case 4:
      var value = new proto.google.api.apikeys.v2.IosKeyRestrictions;
      reader.readMessage(value,proto.google.api.apikeys.v2.IosKeyRestrictions.deserializeBinaryFromReader);
      msg.setIosKeyRestrictions(value);
      break;
    case 5:
      var value = new proto.google.api.apikeys.v2.ApiTarget;
      reader.readMessage(value,proto.google.api.apikeys.v2.ApiTarget.deserializeBinaryFromReader);
      msg.addApiTargets(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.api.apikeys.v2.Restrictions.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.api.apikeys.v2.Restrictions.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.api.apikeys.v2.Restrictions} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.api.apikeys.v2.Restrictions.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBrowserKeyRestrictions();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.google.api.apikeys.v2.BrowserKeyRestrictions.serializeBinaryToWriter
    );
  }
  f = message.getServerKeyRestrictions();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.google.api.apikeys.v2.ServerKeyRestrictions.serializeBinaryToWriter
    );
  }
  f = message.getAndroidKeyRestrictions();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.google.api.apikeys.v2.AndroidKeyRestrictions.serializeBinaryToWriter
    );
  }
  f = message.getIosKeyRestrictions();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.google.api.apikeys.v2.IosKeyRestrictions.serializeBinaryToWriter
    );
  }
  f = message.getApiTargetsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      5,
      f,
      proto.google.api.apikeys.v2.ApiTarget.serializeBinaryToWriter
    );
  }
};


/**
 * optional BrowserKeyRestrictions browser_key_restrictions = 1;
 * @return {?proto.google.api.apikeys.v2.BrowserKeyRestrictions}
 */
proto.google.api.apikeys.v2.Restrictions.prototype.getBrowserKeyRestrictions = function() {
  return /** @type{?proto.google.api.apikeys.v2.BrowserKeyRestrictions} */ (
    jspb.Message.getWrapperField(this, proto.google.api.apikeys.v2.BrowserKeyRestrictions, 1));
};


/**
 * @param {?proto.google.api.apikeys.v2.BrowserKeyRestrictions|undefined} value
 * @return {!proto.google.api.apikeys.v2.Restrictions} returns this
*/
proto.google.api.apikeys.v2.Restrictions.prototype.setBrowserKeyRestrictions = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1, proto.google.api.apikeys.v2.Restrictions.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.api.apikeys.v2.Restrictions} returns this
 */
proto.google.api.apikeys.v2.Restrictions.prototype.clearBrowserKeyRestrictions = function() {
  return this.setBrowserKeyRestrictions(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.api.apikeys.v2.Restrictions.prototype.hasBrowserKeyRestrictions = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional ServerKeyRestrictions server_key_restrictions = 2;
 * @return {?proto.google.api.apikeys.v2.ServerKeyRestrictions}
 */
proto.google.api.apikeys.v2.Restrictions.prototype.getServerKeyRestrictions = function() {
  return /** @type{?proto.google.api.apikeys.v2.ServerKeyRestrictions} */ (
    jspb.Message.getWrapperField(this, proto.google.api.apikeys.v2.ServerKeyRestrictions, 2));
};


/**
 * @param {?proto.google.api.apikeys.v2.ServerKeyRestrictions|undefined} value
 * @return {!proto.google.api.apikeys.v2.Restrictions} returns this
*/
proto.google.api.apikeys.v2.Restrictions.prototype.setServerKeyRestrictions = function(value) {
  return jspb.Message.setOneofWrapperField(this, 2, proto.google.api.apikeys.v2.Restrictions.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.api.apikeys.v2.Restrictions} returns this
 */
proto.google.api.apikeys.v2.Restrictions.prototype.clearServerKeyRestrictions = function() {
  return this.setServerKeyRestrictions(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.api.apikeys.v2.Restrictions.prototype.hasServerKeyRestrictions = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional AndroidKeyRestrictions android_key_restrictions = 3;
 * @return {?proto.google.api.apikeys.v2.AndroidKeyRestrictions}
 */
proto.google.api.apikeys.v2.Restrictions.prototype.getAndroidKeyRestrictions = function() {
  return /** @type{?proto.google.api.apikeys.v2.AndroidKeyRestrictions} */ (
    jspb.Message.getWrapperField(this, proto.google.api.apikeys.v2.AndroidKeyRestrictions, 3));
};


/**
 * @param {?proto.google.api.apikeys.v2.AndroidKeyRestrictions|undefined} value
 * @return {!proto.google.api.apikeys.v2.Restrictions} returns this
*/
proto.google.api.apikeys.v2.Restrictions.prototype.setAndroidKeyRestrictions = function(value) {
  return jspb.Message.setOneofWrapperField(this, 3, proto.google.api.apikeys.v2.Restrictions.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.api.apikeys.v2.Restrictions} returns this
 */
proto.google.api.apikeys.v2.Restrictions.prototype.clearAndroidKeyRestrictions = function() {
  return this.setAndroidKeyRestrictions(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.api.apikeys.v2.Restrictions.prototype.hasAndroidKeyRestrictions = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional IosKeyRestrictions ios_key_restrictions = 4;
 * @return {?proto.google.api.apikeys.v2.IosKeyRestrictions}
 */
proto.google.api.apikeys.v2.Restrictions.prototype.getIosKeyRestrictions = function() {
  return /** @type{?proto.google.api.apikeys.v2.IosKeyRestrictions} */ (
    jspb.Message.getWrapperField(this, proto.google.api.apikeys.v2.IosKeyRestrictions, 4));
};


/**
 * @param {?proto.google.api.apikeys.v2.IosKeyRestrictions|undefined} value
 * @return {!proto.google.api.apikeys.v2.Restrictions} returns this
*/
proto.google.api.apikeys.v2.Restrictions.prototype.setIosKeyRestrictions = function(value) {
  return jspb.Message.setOneofWrapperField(this, 4, proto.google.api.apikeys.v2.Restrictions.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.api.apikeys.v2.Restrictions} returns this
 */
proto.google.api.apikeys.v2.Restrictions.prototype.clearIosKeyRestrictions = function() {
  return this.setIosKeyRestrictions(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.api.apikeys.v2.Restrictions.prototype.hasIosKeyRestrictions = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * repeated ApiTarget api_targets = 5;
 * @return {!Array<!proto.google.api.apikeys.v2.ApiTarget>}
 */
proto.google.api.apikeys.v2.Restrictions.prototype.getApiTargetsList = function() {
  return /** @type{!Array<!proto.google.api.apikeys.v2.ApiTarget>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.google.api.apikeys.v2.ApiTarget, 5));
};


/**
 * @param {!Array<!proto.google.api.apikeys.v2.ApiTarget>} value
 * @return {!proto.google.api.apikeys.v2.Restrictions} returns this
*/
proto.google.api.apikeys.v2.Restrictions.prototype.setApiTargetsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 5, value);
};


/**
 * @param {!proto.google.api.apikeys.v2.ApiTarget=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.api.apikeys.v2.ApiTarget}
 */
proto.google.api.apikeys.v2.Restrictions.prototype.addApiTargets = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 5, opt_value, proto.google.api.apikeys.v2.ApiTarget, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.api.apikeys.v2.Restrictions} returns this
 */
proto.google.api.apikeys.v2.Restrictions.prototype.clearApiTargetsList = function() {
  return this.setApiTargetsList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.google.api.apikeys.v2.BrowserKeyRestrictions.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.api.apikeys.v2.BrowserKeyRestrictions.prototype.toObject = function(opt_includeInstance) {
  return proto.google.api.apikeys.v2.BrowserKeyRestrictions.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.api.apikeys.v2.BrowserKeyRestrictions} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.api.apikeys.v2.BrowserKeyRestrictions.toObject = function(includeInstance, msg) {
  var f, obj = {
    allowedReferrersList: (f = jspb.Message.getRepeatedField(msg, 1)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.api.apikeys.v2.BrowserKeyRestrictions}
 */
proto.google.api.apikeys.v2.BrowserKeyRestrictions.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.api.apikeys.v2.BrowserKeyRestrictions;
  return proto.google.api.apikeys.v2.BrowserKeyRestrictions.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.api.apikeys.v2.BrowserKeyRestrictions} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.api.apikeys.v2.BrowserKeyRestrictions}
 */
proto.google.api.apikeys.v2.BrowserKeyRestrictions.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.addAllowedReferrers(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.api.apikeys.v2.BrowserKeyRestrictions.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.api.apikeys.v2.BrowserKeyRestrictions.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.api.apikeys.v2.BrowserKeyRestrictions} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.api.apikeys.v2.BrowserKeyRestrictions.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAllowedReferrersList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      1,
      f
    );
  }
};


/**
 * repeated string allowed_referrers = 1;
 * @return {!Array<string>}
 */
proto.google.api.apikeys.v2.BrowserKeyRestrictions.prototype.getAllowedReferrersList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 1));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.google.api.apikeys.v2.BrowserKeyRestrictions} returns this
 */
proto.google.api.apikeys.v2.BrowserKeyRestrictions.prototype.setAllowedReferrersList = function(value) {
  return jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.google.api.apikeys.v2.BrowserKeyRestrictions} returns this
 */
proto.google.api.apikeys.v2.BrowserKeyRestrictions.prototype.addAllowedReferrers = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.api.apikeys.v2.BrowserKeyRestrictions} returns this
 */
proto.google.api.apikeys.v2.BrowserKeyRestrictions.prototype.clearAllowedReferrersList = function() {
  return this.setAllowedReferrersList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.google.api.apikeys.v2.ServerKeyRestrictions.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.api.apikeys.v2.ServerKeyRestrictions.prototype.toObject = function(opt_includeInstance) {
  return proto.google.api.apikeys.v2.ServerKeyRestrictions.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.api.apikeys.v2.ServerKeyRestrictions} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.api.apikeys.v2.ServerKeyRestrictions.toObject = function(includeInstance, msg) {
  var f, obj = {
    allowedIpsList: (f = jspb.Message.getRepeatedField(msg, 1)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.api.apikeys.v2.ServerKeyRestrictions}
 */
proto.google.api.apikeys.v2.ServerKeyRestrictions.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.api.apikeys.v2.ServerKeyRestrictions;
  return proto.google.api.apikeys.v2.ServerKeyRestrictions.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.api.apikeys.v2.ServerKeyRestrictions} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.api.apikeys.v2.ServerKeyRestrictions}
 */
proto.google.api.apikeys.v2.ServerKeyRestrictions.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.addAllowedIps(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.api.apikeys.v2.ServerKeyRestrictions.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.api.apikeys.v2.ServerKeyRestrictions.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.api.apikeys.v2.ServerKeyRestrictions} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.api.apikeys.v2.ServerKeyRestrictions.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAllowedIpsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      1,
      f
    );
  }
};


/**
 * repeated string allowed_ips = 1;
 * @return {!Array<string>}
 */
proto.google.api.apikeys.v2.ServerKeyRestrictions.prototype.getAllowedIpsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 1));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.google.api.apikeys.v2.ServerKeyRestrictions} returns this
 */
proto.google.api.apikeys.v2.ServerKeyRestrictions.prototype.setAllowedIpsList = function(value) {
  return jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.google.api.apikeys.v2.ServerKeyRestrictions} returns this
 */
proto.google.api.apikeys.v2.ServerKeyRestrictions.prototype.addAllowedIps = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.api.apikeys.v2.ServerKeyRestrictions} returns this
 */
proto.google.api.apikeys.v2.ServerKeyRestrictions.prototype.clearAllowedIpsList = function() {
  return this.setAllowedIpsList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.google.api.apikeys.v2.AndroidKeyRestrictions.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.api.apikeys.v2.AndroidKeyRestrictions.prototype.toObject = function(opt_includeInstance) {
  return proto.google.api.apikeys.v2.AndroidKeyRestrictions.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.api.apikeys.v2.AndroidKeyRestrictions} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.api.apikeys.v2.AndroidKeyRestrictions.toObject = function(includeInstance, msg) {
  var f, obj = {
    allowedApplicationsList: jspb.Message.toObjectList(msg.getAllowedApplicationsList(),
    proto.google.api.apikeys.v2.AndroidApplication.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.api.apikeys.v2.AndroidKeyRestrictions}
 */
proto.google.api.apikeys.v2.AndroidKeyRestrictions.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.api.apikeys.v2.AndroidKeyRestrictions;
  return proto.google.api.apikeys.v2.AndroidKeyRestrictions.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.api.apikeys.v2.AndroidKeyRestrictions} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.api.apikeys.v2.AndroidKeyRestrictions}
 */
proto.google.api.apikeys.v2.AndroidKeyRestrictions.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.google.api.apikeys.v2.AndroidApplication;
      reader.readMessage(value,proto.google.api.apikeys.v2.AndroidApplication.deserializeBinaryFromReader);
      msg.addAllowedApplications(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.api.apikeys.v2.AndroidKeyRestrictions.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.api.apikeys.v2.AndroidKeyRestrictions.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.api.apikeys.v2.AndroidKeyRestrictions} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.api.apikeys.v2.AndroidKeyRestrictions.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAllowedApplicationsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.google.api.apikeys.v2.AndroidApplication.serializeBinaryToWriter
    );
  }
};


/**
 * repeated AndroidApplication allowed_applications = 1;
 * @return {!Array<!proto.google.api.apikeys.v2.AndroidApplication>}
 */
proto.google.api.apikeys.v2.AndroidKeyRestrictions.prototype.getAllowedApplicationsList = function() {
  return /** @type{!Array<!proto.google.api.apikeys.v2.AndroidApplication>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.google.api.apikeys.v2.AndroidApplication, 1));
};


/**
 * @param {!Array<!proto.google.api.apikeys.v2.AndroidApplication>} value
 * @return {!proto.google.api.apikeys.v2.AndroidKeyRestrictions} returns this
*/
proto.google.api.apikeys.v2.AndroidKeyRestrictions.prototype.setAllowedApplicationsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.google.api.apikeys.v2.AndroidApplication=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.api.apikeys.v2.AndroidApplication}
 */
proto.google.api.apikeys.v2.AndroidKeyRestrictions.prototype.addAllowedApplications = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.google.api.apikeys.v2.AndroidApplication, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.api.apikeys.v2.AndroidKeyRestrictions} returns this
 */
proto.google.api.apikeys.v2.AndroidKeyRestrictions.prototype.clearAllowedApplicationsList = function() {
  return this.setAllowedApplicationsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.api.apikeys.v2.AndroidApplication.prototype.toObject = function(opt_includeInstance) {
  return proto.google.api.apikeys.v2.AndroidApplication.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.api.apikeys.v2.AndroidApplication} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.api.apikeys.v2.AndroidApplication.toObject = function(includeInstance, msg) {
  var f, obj = {
    sha1Fingerprint: jspb.Message.getFieldWithDefault(msg, 1, ""),
    packageName: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.api.apikeys.v2.AndroidApplication}
 */
proto.google.api.apikeys.v2.AndroidApplication.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.api.apikeys.v2.AndroidApplication;
  return proto.google.api.apikeys.v2.AndroidApplication.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.api.apikeys.v2.AndroidApplication} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.api.apikeys.v2.AndroidApplication}
 */
proto.google.api.apikeys.v2.AndroidApplication.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setSha1Fingerprint(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setPackageName(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.api.apikeys.v2.AndroidApplication.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.api.apikeys.v2.AndroidApplication.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.api.apikeys.v2.AndroidApplication} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.api.apikeys.v2.AndroidApplication.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSha1Fingerprint();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getPackageName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string sha1_fingerprint = 1;
 * @return {string}
 */
proto.google.api.apikeys.v2.AndroidApplication.prototype.getSha1Fingerprint = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.api.apikeys.v2.AndroidApplication} returns this
 */
proto.google.api.apikeys.v2.AndroidApplication.prototype.setSha1Fingerprint = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string package_name = 2;
 * @return {string}
 */
proto.google.api.apikeys.v2.AndroidApplication.prototype.getPackageName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.api.apikeys.v2.AndroidApplication} returns this
 */
proto.google.api.apikeys.v2.AndroidApplication.prototype.setPackageName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.google.api.apikeys.v2.IosKeyRestrictions.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.api.apikeys.v2.IosKeyRestrictions.prototype.toObject = function(opt_includeInstance) {
  return proto.google.api.apikeys.v2.IosKeyRestrictions.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.api.apikeys.v2.IosKeyRestrictions} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.api.apikeys.v2.IosKeyRestrictions.toObject = function(includeInstance, msg) {
  var f, obj = {
    allowedBundleIdsList: (f = jspb.Message.getRepeatedField(msg, 1)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.api.apikeys.v2.IosKeyRestrictions}
 */
proto.google.api.apikeys.v2.IosKeyRestrictions.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.api.apikeys.v2.IosKeyRestrictions;
  return proto.google.api.apikeys.v2.IosKeyRestrictions.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.api.apikeys.v2.IosKeyRestrictions} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.api.apikeys.v2.IosKeyRestrictions}
 */
proto.google.api.apikeys.v2.IosKeyRestrictions.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.addAllowedBundleIds(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.api.apikeys.v2.IosKeyRestrictions.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.api.apikeys.v2.IosKeyRestrictions.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.api.apikeys.v2.IosKeyRestrictions} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.api.apikeys.v2.IosKeyRestrictions.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAllowedBundleIdsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      1,
      f
    );
  }
};


/**
 * repeated string allowed_bundle_ids = 1;
 * @return {!Array<string>}
 */
proto.google.api.apikeys.v2.IosKeyRestrictions.prototype.getAllowedBundleIdsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 1));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.google.api.apikeys.v2.IosKeyRestrictions} returns this
 */
proto.google.api.apikeys.v2.IosKeyRestrictions.prototype.setAllowedBundleIdsList = function(value) {
  return jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.google.api.apikeys.v2.IosKeyRestrictions} returns this
 */
proto.google.api.apikeys.v2.IosKeyRestrictions.prototype.addAllowedBundleIds = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.api.apikeys.v2.IosKeyRestrictions} returns this
 */
proto.google.api.apikeys.v2.IosKeyRestrictions.prototype.clearAllowedBundleIdsList = function() {
  return this.setAllowedBundleIdsList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.google.api.apikeys.v2.ApiTarget.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.api.apikeys.v2.ApiTarget.prototype.toObject = function(opt_includeInstance) {
  return proto.google.api.apikeys.v2.ApiTarget.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.api.apikeys.v2.ApiTarget} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.api.apikeys.v2.ApiTarget.toObject = function(includeInstance, msg) {
  var f, obj = {
    service: jspb.Message.getFieldWithDefault(msg, 1, ""),
    methodsList: (f = jspb.Message.getRepeatedField(msg, 2)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.api.apikeys.v2.ApiTarget}
 */
proto.google.api.apikeys.v2.ApiTarget.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.api.apikeys.v2.ApiTarget;
  return proto.google.api.apikeys.v2.ApiTarget.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.api.apikeys.v2.ApiTarget} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.api.apikeys.v2.ApiTarget}
 */
proto.google.api.apikeys.v2.ApiTarget.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setService(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.addMethods(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.api.apikeys.v2.ApiTarget.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.api.apikeys.v2.ApiTarget.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.api.apikeys.v2.ApiTarget} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.api.apikeys.v2.ApiTarget.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getService();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getMethodsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      2,
      f
    );
  }
};


/**
 * optional string service = 1;
 * @return {string}
 */
proto.google.api.apikeys.v2.ApiTarget.prototype.getService = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.api.apikeys.v2.ApiTarget} returns this
 */
proto.google.api.apikeys.v2.ApiTarget.prototype.setService = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * repeated string methods = 2;
 * @return {!Array<string>}
 */
proto.google.api.apikeys.v2.ApiTarget.prototype.getMethodsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 2));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.google.api.apikeys.v2.ApiTarget} returns this
 */
proto.google.api.apikeys.v2.ApiTarget.prototype.setMethodsList = function(value) {
  return jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.google.api.apikeys.v2.ApiTarget} returns this
 */
proto.google.api.apikeys.v2.ApiTarget.prototype.addMethods = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.api.apikeys.v2.ApiTarget} returns this
 */
proto.google.api.apikeys.v2.ApiTarget.prototype.clearMethodsList = function() {
  return this.setMethodsList([]);
};


goog.object.extend(exports, proto.google.api.apikeys.v2);
