/**
 * @fileoverview gRPC-Web generated client stub for google.logging.v2
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.1
// 	protoc              v3.19.1
// source: google/logging/v2/logging_config.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var google_api_annotations_pb = require('../../../google/api/annotations_pb.js')

var google_api_client_pb = require('../../../google/api/client_pb.js')

var google_api_field_behavior_pb = require('../../../google/api/field_behavior_pb.js')

var google_api_resource_pb = require('../../../google/api/resource_pb.js')

var google_longrunning_operations_pb = require('../../../google/longrunning/operations_pb.js')

var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js')

var google_protobuf_field_mask_pb = require('google-protobuf/google/protobuf/field_mask_pb.js')

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js')
const proto = {};
proto.google = {};
proto.google.logging = {};
proto.google.logging.v2 = require('./logging_config_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.google.logging.v2.ConfigServiceV2Client =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.google.logging.v2.ConfigServiceV2PromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.logging.v2.ListBucketsRequest,
 *   !proto.google.logging.v2.ListBucketsResponse>}
 */
const methodDescriptor_ConfigServiceV2_ListBuckets = new grpc.web.MethodDescriptor(
  '/google.logging.v2.ConfigServiceV2/ListBuckets',
  grpc.web.MethodType.UNARY,
  proto.google.logging.v2.ListBucketsRequest,
  proto.google.logging.v2.ListBucketsResponse,
  /**
   * @param {!proto.google.logging.v2.ListBucketsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.google.logging.v2.ListBucketsResponse.deserializeBinary
);


/**
 * @param {!proto.google.logging.v2.ListBucketsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.logging.v2.ListBucketsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.logging.v2.ListBucketsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.google.logging.v2.ConfigServiceV2Client.prototype.listBuckets =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/google.logging.v2.ConfigServiceV2/ListBuckets',
      request,
      metadata || {},
      methodDescriptor_ConfigServiceV2_ListBuckets,
      callback);
};


/**
 * @param {!proto.google.logging.v2.ListBucketsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.logging.v2.ListBucketsResponse>}
 *     Promise that resolves to the response
 */
proto.google.logging.v2.ConfigServiceV2PromiseClient.prototype.listBuckets =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/google.logging.v2.ConfigServiceV2/ListBuckets',
      request,
      metadata || {},
      methodDescriptor_ConfigServiceV2_ListBuckets);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.logging.v2.GetBucketRequest,
 *   !proto.google.logging.v2.LogBucket>}
 */
const methodDescriptor_ConfigServiceV2_GetBucket = new grpc.web.MethodDescriptor(
  '/google.logging.v2.ConfigServiceV2/GetBucket',
  grpc.web.MethodType.UNARY,
  proto.google.logging.v2.GetBucketRequest,
  proto.google.logging.v2.LogBucket,
  /**
   * @param {!proto.google.logging.v2.GetBucketRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.google.logging.v2.LogBucket.deserializeBinary
);


/**
 * @param {!proto.google.logging.v2.GetBucketRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.logging.v2.LogBucket)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.logging.v2.LogBucket>|undefined}
 *     The XHR Node Readable Stream
 */
proto.google.logging.v2.ConfigServiceV2Client.prototype.getBucket =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/google.logging.v2.ConfigServiceV2/GetBucket',
      request,
      metadata || {},
      methodDescriptor_ConfigServiceV2_GetBucket,
      callback);
};


/**
 * @param {!proto.google.logging.v2.GetBucketRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.logging.v2.LogBucket>}
 *     Promise that resolves to the response
 */
proto.google.logging.v2.ConfigServiceV2PromiseClient.prototype.getBucket =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/google.logging.v2.ConfigServiceV2/GetBucket',
      request,
      metadata || {},
      methodDescriptor_ConfigServiceV2_GetBucket);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.logging.v2.CreateBucketRequest,
 *   !proto.google.logging.v2.LogBucket>}
 */
const methodDescriptor_ConfigServiceV2_CreateBucket = new grpc.web.MethodDescriptor(
  '/google.logging.v2.ConfigServiceV2/CreateBucket',
  grpc.web.MethodType.UNARY,
  proto.google.logging.v2.CreateBucketRequest,
  proto.google.logging.v2.LogBucket,
  /**
   * @param {!proto.google.logging.v2.CreateBucketRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.google.logging.v2.LogBucket.deserializeBinary
);


/**
 * @param {!proto.google.logging.v2.CreateBucketRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.logging.v2.LogBucket)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.logging.v2.LogBucket>|undefined}
 *     The XHR Node Readable Stream
 */
proto.google.logging.v2.ConfigServiceV2Client.prototype.createBucket =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/google.logging.v2.ConfigServiceV2/CreateBucket',
      request,
      metadata || {},
      methodDescriptor_ConfigServiceV2_CreateBucket,
      callback);
};


/**
 * @param {!proto.google.logging.v2.CreateBucketRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.logging.v2.LogBucket>}
 *     Promise that resolves to the response
 */
proto.google.logging.v2.ConfigServiceV2PromiseClient.prototype.createBucket =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/google.logging.v2.ConfigServiceV2/CreateBucket',
      request,
      metadata || {},
      methodDescriptor_ConfigServiceV2_CreateBucket);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.logging.v2.UpdateBucketRequest,
 *   !proto.google.logging.v2.LogBucket>}
 */
const methodDescriptor_ConfigServiceV2_UpdateBucket = new grpc.web.MethodDescriptor(
  '/google.logging.v2.ConfigServiceV2/UpdateBucket',
  grpc.web.MethodType.UNARY,
  proto.google.logging.v2.UpdateBucketRequest,
  proto.google.logging.v2.LogBucket,
  /**
   * @param {!proto.google.logging.v2.UpdateBucketRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.google.logging.v2.LogBucket.deserializeBinary
);


/**
 * @param {!proto.google.logging.v2.UpdateBucketRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.logging.v2.LogBucket)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.logging.v2.LogBucket>|undefined}
 *     The XHR Node Readable Stream
 */
proto.google.logging.v2.ConfigServiceV2Client.prototype.updateBucket =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/google.logging.v2.ConfigServiceV2/UpdateBucket',
      request,
      metadata || {},
      methodDescriptor_ConfigServiceV2_UpdateBucket,
      callback);
};


/**
 * @param {!proto.google.logging.v2.UpdateBucketRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.logging.v2.LogBucket>}
 *     Promise that resolves to the response
 */
proto.google.logging.v2.ConfigServiceV2PromiseClient.prototype.updateBucket =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/google.logging.v2.ConfigServiceV2/UpdateBucket',
      request,
      metadata || {},
      methodDescriptor_ConfigServiceV2_UpdateBucket);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.logging.v2.DeleteBucketRequest,
 *   !proto.google.protobuf.Empty>}
 */
const methodDescriptor_ConfigServiceV2_DeleteBucket = new grpc.web.MethodDescriptor(
  '/google.logging.v2.ConfigServiceV2/DeleteBucket',
  grpc.web.MethodType.UNARY,
  proto.google.logging.v2.DeleteBucketRequest,
  google_protobuf_empty_pb.Empty,
  /**
   * @param {!proto.google.logging.v2.DeleteBucketRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  google_protobuf_empty_pb.Empty.deserializeBinary
);


/**
 * @param {!proto.google.logging.v2.DeleteBucketRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.protobuf.Empty)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.protobuf.Empty>|undefined}
 *     The XHR Node Readable Stream
 */
proto.google.logging.v2.ConfigServiceV2Client.prototype.deleteBucket =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/google.logging.v2.ConfigServiceV2/DeleteBucket',
      request,
      metadata || {},
      methodDescriptor_ConfigServiceV2_DeleteBucket,
      callback);
};


/**
 * @param {!proto.google.logging.v2.DeleteBucketRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.protobuf.Empty>}
 *     Promise that resolves to the response
 */
proto.google.logging.v2.ConfigServiceV2PromiseClient.prototype.deleteBucket =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/google.logging.v2.ConfigServiceV2/DeleteBucket',
      request,
      metadata || {},
      methodDescriptor_ConfigServiceV2_DeleteBucket);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.logging.v2.UndeleteBucketRequest,
 *   !proto.google.protobuf.Empty>}
 */
const methodDescriptor_ConfigServiceV2_UndeleteBucket = new grpc.web.MethodDescriptor(
  '/google.logging.v2.ConfigServiceV2/UndeleteBucket',
  grpc.web.MethodType.UNARY,
  proto.google.logging.v2.UndeleteBucketRequest,
  google_protobuf_empty_pb.Empty,
  /**
   * @param {!proto.google.logging.v2.UndeleteBucketRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  google_protobuf_empty_pb.Empty.deserializeBinary
);


/**
 * @param {!proto.google.logging.v2.UndeleteBucketRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.protobuf.Empty)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.protobuf.Empty>|undefined}
 *     The XHR Node Readable Stream
 */
proto.google.logging.v2.ConfigServiceV2Client.prototype.undeleteBucket =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/google.logging.v2.ConfigServiceV2/UndeleteBucket',
      request,
      metadata || {},
      methodDescriptor_ConfigServiceV2_UndeleteBucket,
      callback);
};


/**
 * @param {!proto.google.logging.v2.UndeleteBucketRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.protobuf.Empty>}
 *     Promise that resolves to the response
 */
proto.google.logging.v2.ConfigServiceV2PromiseClient.prototype.undeleteBucket =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/google.logging.v2.ConfigServiceV2/UndeleteBucket',
      request,
      metadata || {},
      methodDescriptor_ConfigServiceV2_UndeleteBucket);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.logging.v2.ListViewsRequest,
 *   !proto.google.logging.v2.ListViewsResponse>}
 */
const methodDescriptor_ConfigServiceV2_ListViews = new grpc.web.MethodDescriptor(
  '/google.logging.v2.ConfigServiceV2/ListViews',
  grpc.web.MethodType.UNARY,
  proto.google.logging.v2.ListViewsRequest,
  proto.google.logging.v2.ListViewsResponse,
  /**
   * @param {!proto.google.logging.v2.ListViewsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.google.logging.v2.ListViewsResponse.deserializeBinary
);


/**
 * @param {!proto.google.logging.v2.ListViewsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.logging.v2.ListViewsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.logging.v2.ListViewsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.google.logging.v2.ConfigServiceV2Client.prototype.listViews =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/google.logging.v2.ConfigServiceV2/ListViews',
      request,
      metadata || {},
      methodDescriptor_ConfigServiceV2_ListViews,
      callback);
};


/**
 * @param {!proto.google.logging.v2.ListViewsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.logging.v2.ListViewsResponse>}
 *     Promise that resolves to the response
 */
proto.google.logging.v2.ConfigServiceV2PromiseClient.prototype.listViews =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/google.logging.v2.ConfigServiceV2/ListViews',
      request,
      metadata || {},
      methodDescriptor_ConfigServiceV2_ListViews);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.logging.v2.GetViewRequest,
 *   !proto.google.logging.v2.LogView>}
 */
const methodDescriptor_ConfigServiceV2_GetView = new grpc.web.MethodDescriptor(
  '/google.logging.v2.ConfigServiceV2/GetView',
  grpc.web.MethodType.UNARY,
  proto.google.logging.v2.GetViewRequest,
  proto.google.logging.v2.LogView,
  /**
   * @param {!proto.google.logging.v2.GetViewRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.google.logging.v2.LogView.deserializeBinary
);


/**
 * @param {!proto.google.logging.v2.GetViewRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.logging.v2.LogView)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.logging.v2.LogView>|undefined}
 *     The XHR Node Readable Stream
 */
proto.google.logging.v2.ConfigServiceV2Client.prototype.getView =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/google.logging.v2.ConfigServiceV2/GetView',
      request,
      metadata || {},
      methodDescriptor_ConfigServiceV2_GetView,
      callback);
};


/**
 * @param {!proto.google.logging.v2.GetViewRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.logging.v2.LogView>}
 *     Promise that resolves to the response
 */
proto.google.logging.v2.ConfigServiceV2PromiseClient.prototype.getView =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/google.logging.v2.ConfigServiceV2/GetView',
      request,
      metadata || {},
      methodDescriptor_ConfigServiceV2_GetView);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.logging.v2.CreateViewRequest,
 *   !proto.google.logging.v2.LogView>}
 */
const methodDescriptor_ConfigServiceV2_CreateView = new grpc.web.MethodDescriptor(
  '/google.logging.v2.ConfigServiceV2/CreateView',
  grpc.web.MethodType.UNARY,
  proto.google.logging.v2.CreateViewRequest,
  proto.google.logging.v2.LogView,
  /**
   * @param {!proto.google.logging.v2.CreateViewRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.google.logging.v2.LogView.deserializeBinary
);


/**
 * @param {!proto.google.logging.v2.CreateViewRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.logging.v2.LogView)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.logging.v2.LogView>|undefined}
 *     The XHR Node Readable Stream
 */
proto.google.logging.v2.ConfigServiceV2Client.prototype.createView =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/google.logging.v2.ConfigServiceV2/CreateView',
      request,
      metadata || {},
      methodDescriptor_ConfigServiceV2_CreateView,
      callback);
};


/**
 * @param {!proto.google.logging.v2.CreateViewRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.logging.v2.LogView>}
 *     Promise that resolves to the response
 */
proto.google.logging.v2.ConfigServiceV2PromiseClient.prototype.createView =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/google.logging.v2.ConfigServiceV2/CreateView',
      request,
      metadata || {},
      methodDescriptor_ConfigServiceV2_CreateView);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.logging.v2.UpdateViewRequest,
 *   !proto.google.logging.v2.LogView>}
 */
const methodDescriptor_ConfigServiceV2_UpdateView = new grpc.web.MethodDescriptor(
  '/google.logging.v2.ConfigServiceV2/UpdateView',
  grpc.web.MethodType.UNARY,
  proto.google.logging.v2.UpdateViewRequest,
  proto.google.logging.v2.LogView,
  /**
   * @param {!proto.google.logging.v2.UpdateViewRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.google.logging.v2.LogView.deserializeBinary
);


/**
 * @param {!proto.google.logging.v2.UpdateViewRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.logging.v2.LogView)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.logging.v2.LogView>|undefined}
 *     The XHR Node Readable Stream
 */
proto.google.logging.v2.ConfigServiceV2Client.prototype.updateView =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/google.logging.v2.ConfigServiceV2/UpdateView',
      request,
      metadata || {},
      methodDescriptor_ConfigServiceV2_UpdateView,
      callback);
};


/**
 * @param {!proto.google.logging.v2.UpdateViewRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.logging.v2.LogView>}
 *     Promise that resolves to the response
 */
proto.google.logging.v2.ConfigServiceV2PromiseClient.prototype.updateView =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/google.logging.v2.ConfigServiceV2/UpdateView',
      request,
      metadata || {},
      methodDescriptor_ConfigServiceV2_UpdateView);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.logging.v2.DeleteViewRequest,
 *   !proto.google.protobuf.Empty>}
 */
const methodDescriptor_ConfigServiceV2_DeleteView = new grpc.web.MethodDescriptor(
  '/google.logging.v2.ConfigServiceV2/DeleteView',
  grpc.web.MethodType.UNARY,
  proto.google.logging.v2.DeleteViewRequest,
  google_protobuf_empty_pb.Empty,
  /**
   * @param {!proto.google.logging.v2.DeleteViewRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  google_protobuf_empty_pb.Empty.deserializeBinary
);


/**
 * @param {!proto.google.logging.v2.DeleteViewRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.protobuf.Empty)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.protobuf.Empty>|undefined}
 *     The XHR Node Readable Stream
 */
proto.google.logging.v2.ConfigServiceV2Client.prototype.deleteView =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/google.logging.v2.ConfigServiceV2/DeleteView',
      request,
      metadata || {},
      methodDescriptor_ConfigServiceV2_DeleteView,
      callback);
};


/**
 * @param {!proto.google.logging.v2.DeleteViewRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.protobuf.Empty>}
 *     Promise that resolves to the response
 */
proto.google.logging.v2.ConfigServiceV2PromiseClient.prototype.deleteView =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/google.logging.v2.ConfigServiceV2/DeleteView',
      request,
      metadata || {},
      methodDescriptor_ConfigServiceV2_DeleteView);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.logging.v2.ListSinksRequest,
 *   !proto.google.logging.v2.ListSinksResponse>}
 */
const methodDescriptor_ConfigServiceV2_ListSinks = new grpc.web.MethodDescriptor(
  '/google.logging.v2.ConfigServiceV2/ListSinks',
  grpc.web.MethodType.UNARY,
  proto.google.logging.v2.ListSinksRequest,
  proto.google.logging.v2.ListSinksResponse,
  /**
   * @param {!proto.google.logging.v2.ListSinksRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.google.logging.v2.ListSinksResponse.deserializeBinary
);


/**
 * @param {!proto.google.logging.v2.ListSinksRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.logging.v2.ListSinksResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.logging.v2.ListSinksResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.google.logging.v2.ConfigServiceV2Client.prototype.listSinks =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/google.logging.v2.ConfigServiceV2/ListSinks',
      request,
      metadata || {},
      methodDescriptor_ConfigServiceV2_ListSinks,
      callback);
};


/**
 * @param {!proto.google.logging.v2.ListSinksRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.logging.v2.ListSinksResponse>}
 *     Promise that resolves to the response
 */
proto.google.logging.v2.ConfigServiceV2PromiseClient.prototype.listSinks =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/google.logging.v2.ConfigServiceV2/ListSinks',
      request,
      metadata || {},
      methodDescriptor_ConfigServiceV2_ListSinks);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.logging.v2.GetSinkRequest,
 *   !proto.google.logging.v2.LogSink>}
 */
const methodDescriptor_ConfigServiceV2_GetSink = new grpc.web.MethodDescriptor(
  '/google.logging.v2.ConfigServiceV2/GetSink',
  grpc.web.MethodType.UNARY,
  proto.google.logging.v2.GetSinkRequest,
  proto.google.logging.v2.LogSink,
  /**
   * @param {!proto.google.logging.v2.GetSinkRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.google.logging.v2.LogSink.deserializeBinary
);


/**
 * @param {!proto.google.logging.v2.GetSinkRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.logging.v2.LogSink)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.logging.v2.LogSink>|undefined}
 *     The XHR Node Readable Stream
 */
proto.google.logging.v2.ConfigServiceV2Client.prototype.getSink =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/google.logging.v2.ConfigServiceV2/GetSink',
      request,
      metadata || {},
      methodDescriptor_ConfigServiceV2_GetSink,
      callback);
};


/**
 * @param {!proto.google.logging.v2.GetSinkRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.logging.v2.LogSink>}
 *     Promise that resolves to the response
 */
proto.google.logging.v2.ConfigServiceV2PromiseClient.prototype.getSink =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/google.logging.v2.ConfigServiceV2/GetSink',
      request,
      metadata || {},
      methodDescriptor_ConfigServiceV2_GetSink);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.logging.v2.CreateSinkRequest,
 *   !proto.google.logging.v2.LogSink>}
 */
const methodDescriptor_ConfigServiceV2_CreateSink = new grpc.web.MethodDescriptor(
  '/google.logging.v2.ConfigServiceV2/CreateSink',
  grpc.web.MethodType.UNARY,
  proto.google.logging.v2.CreateSinkRequest,
  proto.google.logging.v2.LogSink,
  /**
   * @param {!proto.google.logging.v2.CreateSinkRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.google.logging.v2.LogSink.deserializeBinary
);


/**
 * @param {!proto.google.logging.v2.CreateSinkRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.logging.v2.LogSink)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.logging.v2.LogSink>|undefined}
 *     The XHR Node Readable Stream
 */
proto.google.logging.v2.ConfigServiceV2Client.prototype.createSink =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/google.logging.v2.ConfigServiceV2/CreateSink',
      request,
      metadata || {},
      methodDescriptor_ConfigServiceV2_CreateSink,
      callback);
};


/**
 * @param {!proto.google.logging.v2.CreateSinkRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.logging.v2.LogSink>}
 *     Promise that resolves to the response
 */
proto.google.logging.v2.ConfigServiceV2PromiseClient.prototype.createSink =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/google.logging.v2.ConfigServiceV2/CreateSink',
      request,
      metadata || {},
      methodDescriptor_ConfigServiceV2_CreateSink);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.logging.v2.UpdateSinkRequest,
 *   !proto.google.logging.v2.LogSink>}
 */
const methodDescriptor_ConfigServiceV2_UpdateSink = new grpc.web.MethodDescriptor(
  '/google.logging.v2.ConfigServiceV2/UpdateSink',
  grpc.web.MethodType.UNARY,
  proto.google.logging.v2.UpdateSinkRequest,
  proto.google.logging.v2.LogSink,
  /**
   * @param {!proto.google.logging.v2.UpdateSinkRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.google.logging.v2.LogSink.deserializeBinary
);


/**
 * @param {!proto.google.logging.v2.UpdateSinkRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.logging.v2.LogSink)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.logging.v2.LogSink>|undefined}
 *     The XHR Node Readable Stream
 */
proto.google.logging.v2.ConfigServiceV2Client.prototype.updateSink =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/google.logging.v2.ConfigServiceV2/UpdateSink',
      request,
      metadata || {},
      methodDescriptor_ConfigServiceV2_UpdateSink,
      callback);
};


/**
 * @param {!proto.google.logging.v2.UpdateSinkRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.logging.v2.LogSink>}
 *     Promise that resolves to the response
 */
proto.google.logging.v2.ConfigServiceV2PromiseClient.prototype.updateSink =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/google.logging.v2.ConfigServiceV2/UpdateSink',
      request,
      metadata || {},
      methodDescriptor_ConfigServiceV2_UpdateSink);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.logging.v2.DeleteSinkRequest,
 *   !proto.google.protobuf.Empty>}
 */
const methodDescriptor_ConfigServiceV2_DeleteSink = new grpc.web.MethodDescriptor(
  '/google.logging.v2.ConfigServiceV2/DeleteSink',
  grpc.web.MethodType.UNARY,
  proto.google.logging.v2.DeleteSinkRequest,
  google_protobuf_empty_pb.Empty,
  /**
   * @param {!proto.google.logging.v2.DeleteSinkRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  google_protobuf_empty_pb.Empty.deserializeBinary
);


/**
 * @param {!proto.google.logging.v2.DeleteSinkRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.protobuf.Empty)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.protobuf.Empty>|undefined}
 *     The XHR Node Readable Stream
 */
proto.google.logging.v2.ConfigServiceV2Client.prototype.deleteSink =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/google.logging.v2.ConfigServiceV2/DeleteSink',
      request,
      metadata || {},
      methodDescriptor_ConfigServiceV2_DeleteSink,
      callback);
};


/**
 * @param {!proto.google.logging.v2.DeleteSinkRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.protobuf.Empty>}
 *     Promise that resolves to the response
 */
proto.google.logging.v2.ConfigServiceV2PromiseClient.prototype.deleteSink =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/google.logging.v2.ConfigServiceV2/DeleteSink',
      request,
      metadata || {},
      methodDescriptor_ConfigServiceV2_DeleteSink);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.logging.v2.ListExclusionsRequest,
 *   !proto.google.logging.v2.ListExclusionsResponse>}
 */
const methodDescriptor_ConfigServiceV2_ListExclusions = new grpc.web.MethodDescriptor(
  '/google.logging.v2.ConfigServiceV2/ListExclusions',
  grpc.web.MethodType.UNARY,
  proto.google.logging.v2.ListExclusionsRequest,
  proto.google.logging.v2.ListExclusionsResponse,
  /**
   * @param {!proto.google.logging.v2.ListExclusionsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.google.logging.v2.ListExclusionsResponse.deserializeBinary
);


/**
 * @param {!proto.google.logging.v2.ListExclusionsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.logging.v2.ListExclusionsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.logging.v2.ListExclusionsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.google.logging.v2.ConfigServiceV2Client.prototype.listExclusions =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/google.logging.v2.ConfigServiceV2/ListExclusions',
      request,
      metadata || {},
      methodDescriptor_ConfigServiceV2_ListExclusions,
      callback);
};


/**
 * @param {!proto.google.logging.v2.ListExclusionsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.logging.v2.ListExclusionsResponse>}
 *     Promise that resolves to the response
 */
proto.google.logging.v2.ConfigServiceV2PromiseClient.prototype.listExclusions =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/google.logging.v2.ConfigServiceV2/ListExclusions',
      request,
      metadata || {},
      methodDescriptor_ConfigServiceV2_ListExclusions);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.logging.v2.GetExclusionRequest,
 *   !proto.google.logging.v2.LogExclusion>}
 */
const methodDescriptor_ConfigServiceV2_GetExclusion = new grpc.web.MethodDescriptor(
  '/google.logging.v2.ConfigServiceV2/GetExclusion',
  grpc.web.MethodType.UNARY,
  proto.google.logging.v2.GetExclusionRequest,
  proto.google.logging.v2.LogExclusion,
  /**
   * @param {!proto.google.logging.v2.GetExclusionRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.google.logging.v2.LogExclusion.deserializeBinary
);


/**
 * @param {!proto.google.logging.v2.GetExclusionRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.logging.v2.LogExclusion)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.logging.v2.LogExclusion>|undefined}
 *     The XHR Node Readable Stream
 */
proto.google.logging.v2.ConfigServiceV2Client.prototype.getExclusion =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/google.logging.v2.ConfigServiceV2/GetExclusion',
      request,
      metadata || {},
      methodDescriptor_ConfigServiceV2_GetExclusion,
      callback);
};


/**
 * @param {!proto.google.logging.v2.GetExclusionRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.logging.v2.LogExclusion>}
 *     Promise that resolves to the response
 */
proto.google.logging.v2.ConfigServiceV2PromiseClient.prototype.getExclusion =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/google.logging.v2.ConfigServiceV2/GetExclusion',
      request,
      metadata || {},
      methodDescriptor_ConfigServiceV2_GetExclusion);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.logging.v2.CreateExclusionRequest,
 *   !proto.google.logging.v2.LogExclusion>}
 */
const methodDescriptor_ConfigServiceV2_CreateExclusion = new grpc.web.MethodDescriptor(
  '/google.logging.v2.ConfigServiceV2/CreateExclusion',
  grpc.web.MethodType.UNARY,
  proto.google.logging.v2.CreateExclusionRequest,
  proto.google.logging.v2.LogExclusion,
  /**
   * @param {!proto.google.logging.v2.CreateExclusionRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.google.logging.v2.LogExclusion.deserializeBinary
);


/**
 * @param {!proto.google.logging.v2.CreateExclusionRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.logging.v2.LogExclusion)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.logging.v2.LogExclusion>|undefined}
 *     The XHR Node Readable Stream
 */
proto.google.logging.v2.ConfigServiceV2Client.prototype.createExclusion =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/google.logging.v2.ConfigServiceV2/CreateExclusion',
      request,
      metadata || {},
      methodDescriptor_ConfigServiceV2_CreateExclusion,
      callback);
};


/**
 * @param {!proto.google.logging.v2.CreateExclusionRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.logging.v2.LogExclusion>}
 *     Promise that resolves to the response
 */
proto.google.logging.v2.ConfigServiceV2PromiseClient.prototype.createExclusion =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/google.logging.v2.ConfigServiceV2/CreateExclusion',
      request,
      metadata || {},
      methodDescriptor_ConfigServiceV2_CreateExclusion);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.logging.v2.UpdateExclusionRequest,
 *   !proto.google.logging.v2.LogExclusion>}
 */
const methodDescriptor_ConfigServiceV2_UpdateExclusion = new grpc.web.MethodDescriptor(
  '/google.logging.v2.ConfigServiceV2/UpdateExclusion',
  grpc.web.MethodType.UNARY,
  proto.google.logging.v2.UpdateExclusionRequest,
  proto.google.logging.v2.LogExclusion,
  /**
   * @param {!proto.google.logging.v2.UpdateExclusionRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.google.logging.v2.LogExclusion.deserializeBinary
);


/**
 * @param {!proto.google.logging.v2.UpdateExclusionRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.logging.v2.LogExclusion)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.logging.v2.LogExclusion>|undefined}
 *     The XHR Node Readable Stream
 */
proto.google.logging.v2.ConfigServiceV2Client.prototype.updateExclusion =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/google.logging.v2.ConfigServiceV2/UpdateExclusion',
      request,
      metadata || {},
      methodDescriptor_ConfigServiceV2_UpdateExclusion,
      callback);
};


/**
 * @param {!proto.google.logging.v2.UpdateExclusionRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.logging.v2.LogExclusion>}
 *     Promise that resolves to the response
 */
proto.google.logging.v2.ConfigServiceV2PromiseClient.prototype.updateExclusion =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/google.logging.v2.ConfigServiceV2/UpdateExclusion',
      request,
      metadata || {},
      methodDescriptor_ConfigServiceV2_UpdateExclusion);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.logging.v2.DeleteExclusionRequest,
 *   !proto.google.protobuf.Empty>}
 */
const methodDescriptor_ConfigServiceV2_DeleteExclusion = new grpc.web.MethodDescriptor(
  '/google.logging.v2.ConfigServiceV2/DeleteExclusion',
  grpc.web.MethodType.UNARY,
  proto.google.logging.v2.DeleteExclusionRequest,
  google_protobuf_empty_pb.Empty,
  /**
   * @param {!proto.google.logging.v2.DeleteExclusionRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  google_protobuf_empty_pb.Empty.deserializeBinary
);


/**
 * @param {!proto.google.logging.v2.DeleteExclusionRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.protobuf.Empty)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.protobuf.Empty>|undefined}
 *     The XHR Node Readable Stream
 */
proto.google.logging.v2.ConfigServiceV2Client.prototype.deleteExclusion =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/google.logging.v2.ConfigServiceV2/DeleteExclusion',
      request,
      metadata || {},
      methodDescriptor_ConfigServiceV2_DeleteExclusion,
      callback);
};


/**
 * @param {!proto.google.logging.v2.DeleteExclusionRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.protobuf.Empty>}
 *     Promise that resolves to the response
 */
proto.google.logging.v2.ConfigServiceV2PromiseClient.prototype.deleteExclusion =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/google.logging.v2.ConfigServiceV2/DeleteExclusion',
      request,
      metadata || {},
      methodDescriptor_ConfigServiceV2_DeleteExclusion);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.logging.v2.GetCmekSettingsRequest,
 *   !proto.google.logging.v2.CmekSettings>}
 */
const methodDescriptor_ConfigServiceV2_GetCmekSettings = new grpc.web.MethodDescriptor(
  '/google.logging.v2.ConfigServiceV2/GetCmekSettings',
  grpc.web.MethodType.UNARY,
  proto.google.logging.v2.GetCmekSettingsRequest,
  proto.google.logging.v2.CmekSettings,
  /**
   * @param {!proto.google.logging.v2.GetCmekSettingsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.google.logging.v2.CmekSettings.deserializeBinary
);


/**
 * @param {!proto.google.logging.v2.GetCmekSettingsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.logging.v2.CmekSettings)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.logging.v2.CmekSettings>|undefined}
 *     The XHR Node Readable Stream
 */
proto.google.logging.v2.ConfigServiceV2Client.prototype.getCmekSettings =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/google.logging.v2.ConfigServiceV2/GetCmekSettings',
      request,
      metadata || {},
      methodDescriptor_ConfigServiceV2_GetCmekSettings,
      callback);
};


/**
 * @param {!proto.google.logging.v2.GetCmekSettingsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.logging.v2.CmekSettings>}
 *     Promise that resolves to the response
 */
proto.google.logging.v2.ConfigServiceV2PromiseClient.prototype.getCmekSettings =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/google.logging.v2.ConfigServiceV2/GetCmekSettings',
      request,
      metadata || {},
      methodDescriptor_ConfigServiceV2_GetCmekSettings);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.logging.v2.UpdateCmekSettingsRequest,
 *   !proto.google.logging.v2.CmekSettings>}
 */
const methodDescriptor_ConfigServiceV2_UpdateCmekSettings = new grpc.web.MethodDescriptor(
  '/google.logging.v2.ConfigServiceV2/UpdateCmekSettings',
  grpc.web.MethodType.UNARY,
  proto.google.logging.v2.UpdateCmekSettingsRequest,
  proto.google.logging.v2.CmekSettings,
  /**
   * @param {!proto.google.logging.v2.UpdateCmekSettingsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.google.logging.v2.CmekSettings.deserializeBinary
);


/**
 * @param {!proto.google.logging.v2.UpdateCmekSettingsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.logging.v2.CmekSettings)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.logging.v2.CmekSettings>|undefined}
 *     The XHR Node Readable Stream
 */
proto.google.logging.v2.ConfigServiceV2Client.prototype.updateCmekSettings =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/google.logging.v2.ConfigServiceV2/UpdateCmekSettings',
      request,
      metadata || {},
      methodDescriptor_ConfigServiceV2_UpdateCmekSettings,
      callback);
};


/**
 * @param {!proto.google.logging.v2.UpdateCmekSettingsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.logging.v2.CmekSettings>}
 *     Promise that resolves to the response
 */
proto.google.logging.v2.ConfigServiceV2PromiseClient.prototype.updateCmekSettings =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/google.logging.v2.ConfigServiceV2/UpdateCmekSettings',
      request,
      metadata || {},
      methodDescriptor_ConfigServiceV2_UpdateCmekSettings);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.logging.v2.GetSettingsRequest,
 *   !proto.google.logging.v2.Settings>}
 */
const methodDescriptor_ConfigServiceV2_GetSettings = new grpc.web.MethodDescriptor(
  '/google.logging.v2.ConfigServiceV2/GetSettings',
  grpc.web.MethodType.UNARY,
  proto.google.logging.v2.GetSettingsRequest,
  proto.google.logging.v2.Settings,
  /**
   * @param {!proto.google.logging.v2.GetSettingsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.google.logging.v2.Settings.deserializeBinary
);


/**
 * @param {!proto.google.logging.v2.GetSettingsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.logging.v2.Settings)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.logging.v2.Settings>|undefined}
 *     The XHR Node Readable Stream
 */
proto.google.logging.v2.ConfigServiceV2Client.prototype.getSettings =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/google.logging.v2.ConfigServiceV2/GetSettings',
      request,
      metadata || {},
      methodDescriptor_ConfigServiceV2_GetSettings,
      callback);
};


/**
 * @param {!proto.google.logging.v2.GetSettingsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.logging.v2.Settings>}
 *     Promise that resolves to the response
 */
proto.google.logging.v2.ConfigServiceV2PromiseClient.prototype.getSettings =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/google.logging.v2.ConfigServiceV2/GetSettings',
      request,
      metadata || {},
      methodDescriptor_ConfigServiceV2_GetSettings);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.logging.v2.UpdateSettingsRequest,
 *   !proto.google.logging.v2.Settings>}
 */
const methodDescriptor_ConfigServiceV2_UpdateSettings = new grpc.web.MethodDescriptor(
  '/google.logging.v2.ConfigServiceV2/UpdateSettings',
  grpc.web.MethodType.UNARY,
  proto.google.logging.v2.UpdateSettingsRequest,
  proto.google.logging.v2.Settings,
  /**
   * @param {!proto.google.logging.v2.UpdateSettingsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.google.logging.v2.Settings.deserializeBinary
);


/**
 * @param {!proto.google.logging.v2.UpdateSettingsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.logging.v2.Settings)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.logging.v2.Settings>|undefined}
 *     The XHR Node Readable Stream
 */
proto.google.logging.v2.ConfigServiceV2Client.prototype.updateSettings =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/google.logging.v2.ConfigServiceV2/UpdateSettings',
      request,
      metadata || {},
      methodDescriptor_ConfigServiceV2_UpdateSettings,
      callback);
};


/**
 * @param {!proto.google.logging.v2.UpdateSettingsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.logging.v2.Settings>}
 *     Promise that resolves to the response
 */
proto.google.logging.v2.ConfigServiceV2PromiseClient.prototype.updateSettings =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/google.logging.v2.ConfigServiceV2/UpdateSettings',
      request,
      metadata || {},
      methodDescriptor_ConfigServiceV2_UpdateSettings);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.logging.v2.CopyLogEntriesRequest,
 *   !proto.google.longrunning.Operation>}
 */
const methodDescriptor_ConfigServiceV2_CopyLogEntries = new grpc.web.MethodDescriptor(
  '/google.logging.v2.ConfigServiceV2/CopyLogEntries',
  grpc.web.MethodType.UNARY,
  proto.google.logging.v2.CopyLogEntriesRequest,
  google_longrunning_operations_pb.Operation,
  /**
   * @param {!proto.google.logging.v2.CopyLogEntriesRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  google_longrunning_operations_pb.Operation.deserializeBinary
);


/**
 * @param {!proto.google.logging.v2.CopyLogEntriesRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.longrunning.Operation)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.longrunning.Operation>|undefined}
 *     The XHR Node Readable Stream
 */
proto.google.logging.v2.ConfigServiceV2Client.prototype.copyLogEntries =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/google.logging.v2.ConfigServiceV2/CopyLogEntries',
      request,
      metadata || {},
      methodDescriptor_ConfigServiceV2_CopyLogEntries,
      callback);
};


/**
 * @param {!proto.google.logging.v2.CopyLogEntriesRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.longrunning.Operation>}
 *     Promise that resolves to the response
 */
proto.google.logging.v2.ConfigServiceV2PromiseClient.prototype.copyLogEntries =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/google.logging.v2.ConfigServiceV2/CopyLogEntries',
      request,
      metadata || {},
      methodDescriptor_ConfigServiceV2_CopyLogEntries);
};


module.exports = proto.google.logging.v2;

